### ISSUE TITLE
DnD drops wrong track when playlist is scrolled

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1319] opened 2015-11-05 00:31 UTC
Regression?  Doesn't happen in my base 0.6.2 build.

In one test, dragging a selected track down until it scrolls off the top of the list, then dropping, drops the wrong track.  It appears to drop the first visible track at the top of the drawing area.

In another test, dragging a track in a playlist that is partially scrolled down, then dropping at the top of the page, moves a different track.  The first track in the playlist is moved even though it isn't selected?  Or is it the first visible track again?

In another test, there are three groups.  The middle one has album art taller than the track list, so there is blank space after the rows.  Drag a track from the first group until the pointer goes past the last track of the middle group, then the DND marker moves to the start of the third group.  OK so far.  Move the pointer a little lower and the marker skips to after the second track in the third group even though the pointer is still over the blank space of the second group.

**Comment by cboxdoerfer** [comment] 2015-11-05 05:48
Thx, didn't know about the third one. The first two bugs I already fixed in my branches but haven't pushed yet.

**Comment by Lithopsian** [comment] 2015-11-06 15:41
Is this really fixed by the pull request?  I have grabbed the changes but still see the problems.

**Comment by Alexey-Yakovenko** [comment] 2015-11-06 18:25
I don't know, it was an auto-close, because the commit messages contain the `fix #1319`

**Comment by cboxdoerfer** [comment] 2015-11-06 19:11
What's not working?

**Comment by Lithopsian** [comment] 2015-11-06 20:12
Well basically nothing is working, that's why I asked.  I just cloned a brand new repo from trunk to make sure I was getting the right code.  Drag'n'drop, with the playlist scrolled down, moves the wrong item.  To the right place :)  Apparently the item at the top of the visible area, or possibly the one immediately off the top of the screen, is dropped instead of the one that was selected and dragged.

The marker issue seems slightly changed.  It doesn't ever skip to the second item in the next group any more so far as I can tell, but something different happens.  Dragging down over the album art column, the marker moves through the group as expected.  Then at the end it skips to the top of the next group, probably also expected.  Then scrolling down past the last item in the group, the marker skips back up to above the last item in the current group.  Maybe intentional?

**Comment by cboxdoerfer** [comment] 2015-11-06 20:24
> Well basically nothing is working, that's why I asked. I just cloned a brand new repo from trunk to make sure I was getting the right code. Drag'n'drop, with the playlist scrolled down, moves the wrong item. To the right place :) Apparently the item at the top of the visible area, or possibly the one immediately off the top of the screen, is dropped instead of the one that was selected and dragged.

Hm, I really can't reproduce that.

> The marker issue seems slightly changed. It doesn't ever skip to the second item in the next group any more so far as I can tell, but something different happens. Dragging down over the album art column, the marker moves through the group as expected. Then at the end it skips to the top of the next group, probably also expected. Then scrolling down past the last item in the group, the marker skips back up to above the last item in the current group. Maybe intentional?

Ah, no that's another bug. It wasn't clear to me that you meant the album art column. But I can reproduce that and fix is easy.

**Comment by Lithopsian** [comment] 2015-11-06 20:43
Here's what I do, in pictures.  Drag a track and drop it.  A different track, apparently the one from the top of the screen, is dropped.
![drag](https://cloud.githubusercontent.com/assets/7702742/11008194/e429e764-84c6-11e5-8aa8-339b207fcc89.png)
![drop](https://cloud.githubusercontent.com/assets/7702742/11008195/e439911e-84c6-11e5-9a91-8ac7c4feea6a.png)

**Comment by cboxdoerfer** [comment] 2015-11-06 20:58
Damn this is weird. I tried to mimic the situation in your screenshots as close as I could, but still can't reproduce the bug. If you start with a new clean config (i.e. without grouping, ...), does it still happen?

**Comment by Lithopsian** [comment] 2015-11-06 22:28
I debugged for a bit.  It was driving me up the wall, everything looked perfect but the wrong answer came back for the list of selected items, but I found it.

Take a look in ddb_listview_list_mouse1_released() in master.  It goes in to the first set of nested ifs and calls ddb_listview_select_single().  The playlist is not redrawn, so you don't notice, but the wrong item is now selected, and then gets moved.

Ungrouped, it always seems to select the first item whether the list is scrolled or not.   Grouped, it is more complex and selects the cursor position when unscrolled (but still deselects multiple items), and gets more messed up when scrolled.

**Comment by cboxdoerfer** [comment] 2015-11-07 08:50
Thx, really appreciate that.  this should be enough information to fix it.

**Closed** 2015-11-07 13:54 UTC

**Comment by cboxdoerfer** [comment] 2015-11-07 15:33
@Lithopsian, please let me know if the patches fixed those issues.

**Comment by Lithopsian** [comment] 2015-11-07 20:15
I quickly checked the basic problems I was having and they seem fixed.  Did you also fix the way the marker moves over album art?  I'm not seeing any weird jumping any more.

I'll have a more detailed play about tomorrow and see if I can find anything else.

**Comment by cboxdoerfer** [comment] 2015-11-07 20:28
> Did you also fix the way the marker moves over album art? I'm not seeing any weird jumping any more.

Yes.

Ok thx, let me know if you find anything.

**Comment by Lithopsian** [comment] 2015-11-08 23:22
I think you've cracked it.  The only tiny thing I spotted is an odd (de-)selection behaviour that didn't used to happen.  With cursor follows playback enabled, any selected tracks will normally be de-selected when a track changes, and the new playing track becomes the single selection.  However, if you are on a different playlist when that happens, the new track is just added to any existing selection.
