### ISSUE TITLE
add hotkey for opening track properties

### ISSUE THREAD

**Issue by shaforostoff** [Alexey-Yakovenko/deadbeef#1520] opened 2016-03-27 00:52 UTC
pressing ctrl+c, ctrl+x and ctrl+v does nothing. in foobar2000 it copies/cuts selected track(s), ctrl+v pastes them above the current one. this works across playlists and foobar2000 instances

also alt+enter should open tag editing window.

**Comment by Alexey-Yakovenko** [comment] 2016-03-27 10:16
deadbeef doesn't support copy&paste (yet), and this is a duplicate of #606

**Comment by shaforostoff** [comment] 2016-03-27 13:48
at least deadbeef supports track info, and there is no shortcut for it

**Comment by Alexey-Yakovenko** [comment] 2016-03-27 21:43
now it's also a duplicate of #1522

**Closed by Alexey-Yakovenko** 2016-03-27 21:43 UTC
Labels: enhancement
