### ISSUE TITLE
Clang 4.0 complains about libtool and --tag

### ISSUE THREAD

**Issue by 38github** [Alexey-Yakovenko/deadbeef#1761] opened 2017-05-03 11:45 UTC
Under Arch Linux x86_64 I am trying to compile Deadbeef using their PKGBUILD system. I have configured the system to use Clang 4.0 and LTO but this gives me the following when compiling Deadbeef:
```
*** Warning: Linking the shared library ddb_gui_GTK2.la against the
*** static library ../libparser/libparser.a is not portable!
  OBJCLD ddb_gui_GTK3.la
libtool: link: unable to infer tagged configuration
libtool: link: specify a tag with `--tag'
make[2]: *** [Makefile:715: ddb_gui_GTK3.la] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/fff/makepkg/deadbeef/0.7.2-2/src/deadbeef-0.7.2/plugins/gtkui'
make[1]: *** [Makefile:769: all-recursive] Error 1
make[1]: Leaving directory '/home/fff/makepkg/deadbeef/0.7.2-2/src/deadbeef-0.7.2'
make: *** [Makefile:527: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```
Does someone know what should be done do to successfully compile Deadbeef using my setup? Thanks!

**Comment by Alexey-Yakovenko** [comment] 2017-05-03 14:37
Seems like a compatibility issue of libtool vs clang, which is unlikely to have anything with deadbeef itself.

It looks like automake or libtool (wrongly) detects that GTKUI sources as ObjectiveC, and attempts to use OBJCLD, which is not available on linux.

The problem appears with [other projects](https://github.com/bitcoin/bitcoin/issues/4993), and they patch them with adding this:

```
qt_bitcoin_qt_LIBTOOLFLAGS = --tag CXX
```

It might help in your case too, but use `C` instead of `CXX`, as GTKUI doesn't use C++.

**Comment by Alexey-Yakovenko** [comment] 2017-05-03 14:38
Another thing that could help is to remove these lines from Makefile.am:

```
if OS_OSX
osx_sources = retina.m
endif
```

(obviously, remember to run autoreconf, configure and friends after modifying those files)

**Comment by Alexey-Yakovenko** [comment] 2017-05-03 14:41
I pushed the fix with the latter change on both master and 0.7, I think this should un-confuse libtool.

**Closed by Alexey-Yakovenko** 2017-05-03 14:41 UTC

**Comment by 38github** [comment] 2017-05-03 17:35
Thank you so much for the amazing help, Alexey!

**Comment by Alexey-Yakovenko** [comment] 2017-05-03 17:37
did it work?

**Comment by 38github** [comment] 2017-05-03 17:37
I just donated a very small sum of money. Support like yours deserves it and especially for "noobs" like me.

**Comment by 38github** [comment] 2017-05-03 17:38
I will try it out but I have to ask if compiling from git is the same as using either master?

**Comment by Alexey-Yakovenko** [comment] 2017-05-03 17:42
It's almost the same as compiling from tarball, but obviously you would not be using PKGBUILD..

you need to install git, clone this repository, change to the repository directory, then run
```
git checkout 0.7
./autogen.sh
./configure
make
sudo make install
```

This would install to `/usr/local`.

You'd need to set up any extra parameters the same way as PKGBUILD does (I don't know the details).

And thanks for the donation. Maybe it's too early though, before you even tried if the fix helped at all.

Please let me know if the problem is still there.

**Comment by 38github** [comment] 2017-05-03 18:30
Being a beginner I used what is easy for me and that is the deadbeef-git package under AUR in Arch Linux and IT COMPILED! I do wonder though if that is because it maybe didn't compile the GTK3 feature in Deadbeef. I am making that guess because I can only choose GTK2 under GUI.

**Comment by Alexey-Yakovenko** [comment] 2017-05-03 18:33
Yeah, it explicitly disables gtk3 with `--disable-gtk3`
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=deadbeef-git

and it doesn't use 0.7 branch -- it builds from master, which is probably not what you want (it's a cutting edge development version, which has way too many things broken).

**Comment by 38github** [comment] 2017-05-03 18:39
I downloaded the 0.7 branch but understood quite fast that I do not know how to setup the compiling outside of PKGBUILD's to use Clang instead of GCC.

I do wonder though. If I compile from the master and remove --disable-gtk3, will your recent change be used during the compiling?

**Comment by Alexey-Yakovenko** [comment] 2017-05-03 18:43
You can do this, yes.
You can also change the "source" line in PKGBUILD like this:

```
source=('git+https://github.com/Alexey-Yakovenko/deadbeef#branch=0.7')
```

This should use 0.7 branch then.

**Comment by Alexey-Yakovenko** [comment] 2017-05-03 18:46
just FYI: 0.7 branch contains the stable version of 0.7.2 + several bugfixes on top, compared to 0.7.2 tarball.

**Comment by 38github** [comment] 2017-05-03 18:46
Thanks for the 0.7 branch tip. The compiling of master branch did work! Thank you so much, Alexey!

**Comment by Alexey-Yakovenko** [comment] 2017-05-03 18:46
np
