### ISSUE TITLE
column autoresize gets messed up at startup for maximized window

### ISSUE THREAD

**Issue by ufovsalien** [Alexey-Yakovenko/deadbeef#1464] opened 2016-02-01 17:17 UTC
Cover part of config rewrites with bigger px values mostly every time, and sometimes cover (default too) opens with enormous size and breaks another columns size too.
```
alsa.buffer 8192  
alsa.freeonstop 0  
alsa.period 1024  
alsa.resample 0  
artwork.cache.period 24  
artwork.enable_albumartorg 0  
artwork.enable_embedded 1  
artwork.enable_lastfm 0  
artwork.enable_localfolder 1  
artwork.enable_musicbrainz 0  
artwork.enable_wos 0  
artwork.filemask *cover*.jpg;*front*.jpg;*folder*.jpg;*cover*.png;*front*.png;*folder*.png  
artwork.missing_artwork 1 
artwork.scale_towards_longer 1  
cli_add_playlist_name Default
cli_add_to_specific_playlist 1
close_send_to_tray 1
deadbeef_version devel
gtkui.autoresize_columns 1
gtkui.columns.playlist [{"title":"Cover","id":"8","format":"","size":"200","align":"0","color_override":"0","color":"#ff000000"},{"title":"#","id":"-1","format":"%track%","size":"50","align":"2","color_override":"0","color":"#ff000000"},{"title":"Title","id":"-1","format":"%title%","size":"600","align":"2","color_override":"0","color":"#ff000000"},{"title":"Duration","id":"-1","format":"%playback_time% | %length%","size":"150","align":"2","color_override":"0","color":"#ff000000"},{"title":"Codec","id":"-1","format":"%codec%","size":"150","align":"0","color_override":"0","color":"#ff4d4d4d"},{"title":"Samplerate","id":"-1","format":"%samplerate%","size":"150","align":"0","color_override":"0","color":"#ff4d4d4d"}]
gtkui.embolden_current_track 1
gtkui.embolden_selected_tracks 0
gtkui.hide_remove_from_disk 1
gtkui.hide_tray_icon 1
gtkui.italic_current_track 0
gtkui.italic_selected_tracks 0
gtkui.layout.0.6.2 playlist hideheaders=0 {}
gtkui.mmb_delete_playlist 0
gtkui.name_playlist_from_folder 1
gtkui.override_bar_colors 0
gtkui.override_listview_colors 0
gtkui.override_tabstrip_colors 0
gtkui.playlist.group_by %album artist% - [(%year%) ]%album%
gtkui.statusbar.visible 0
gtkui.tabscroll 0
gtkui.titlebar_playing %a - %t
gtkui.titlebar_stopped Stopped
gui_plugin GTK2
hotkey.key01 "Ctrl f" 0 0 find
hotkey.key02 "Ctrl o" 0 0 open_files
hotkey.key03 "Ctrl q" 0 0 quit
hotkey.key04 "Ctrl n" 0 0 new_playlist
hotkey.key05 "Ctrl a" 0 0 select_all
hotkey.key06 "Escape" 0 0 deselect_all
hotkey.key07 "Ctrl m" 0 0 toggle_stop_after_current
hotkey.key08 "Ctrl j" 0 0 jump_to_current_track
hotkey.key09 "F1" 0 0 help
hotkey.key10 "Delete" 1 0 remove_from_playlist
hotkey.key11 "Ctrl w" 0 0 remove_current_playlist
hotkey.key12 "Return" 0 0 play
hotkey.key13 "Ctrl p" 0 0 toggle_pause
hotkey.key14 "Alt 1" 0 0 playlist1
hotkey.key15 "Alt 2" 0 0 playlist2
hotkey.key16 "Alt 3" 0 0 playlist3
hotkey.key17 "Alt 4" 0 0 playlist4
hotkey.key18 "Alt 5" 0 0 playlist5
hotkey.key19 "Alt 6" 0 0 playlist6
hotkey.key20 "Alt 7" 0 0 playlist7
hotkey.key21 "Alt 8" 0 0 playlist8
hotkey.key22 "Alt 9" 0 0 playlist9
hotkey.key23 "Alt 0" 0 0 playlist10
hotkey.key24 "XF86AudioPrev" 0 1 prev
hotkey.key25 "XF86AudioPlay" 0 1 toggle_pause
hotkey.key26 "XF86AudioStop" 0 1 stop
hotkey.key27 "XF86AudioNext" 0 1 next
hotkey.key28 "n" 0 0 playback_random
hotkey.key29 "Ctrl k" 0 0 toggle_stop_after_album
hotkey.key30 "XF86Tools" 0 1 sort_tracknr
hotkey.key31 "Super F4" 0 1 sort_album
hotkey.key32 "Super F6" 0 1 seek_5s_fwd
hotkey.key33 "Super F5" 0 1 seek_5s_back
hotkey.key34 "Ctrl F6" 0 1 seek_5p_fwd
hotkey.key35 "Ctrl F5" 0 1 seek_5p_back
hotkey.key36 "Ctrl F4" 0 1 jump_to_current_track
hotkey.key37 "Super F8" 3 1 lfm_lookup
hotkeys_created 1
ignore_archives 1
junk.enable_cp1251_detection 1
junk.enable_shift_jis_detection 0
mainwin.geometry.h 350
mainwin.geometry.maximized 1
mainwin.geometry.w 500
mainwin.geometry.x 1
mainwin.geometry.y 2
network.http_user_agent Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20100101 Firefox/31.0
notify.albumart 1
notify.albumart_size 64
notify.enable 1
notify.format %t
notify.format_content %a - %b
output_plugin PulseAudio output plugin
playback.loop 1
playback.order 0
playback.volume 0.0000000
playlist.current 0
playlist.cursor.0 5
playlist.pin.groups 1
playlist.scroll.0 0
playlist.scroll.cursorfollowplayback 1
prefwin.geometry.h 486
prefwin.geometry.w 607
prefwin.geometry.x 380
prefwin.geometry.y 111
pulse.buffersize 8192
pulse.serveraddr default
replaygain_mode 0
replaygain_scale 1
resume.paused 0
resume.playlist 0
resume.position 36.608284
resume.track 5
resume_last_session 0
streamer.8_to_16 1
trkproperties.geometry.h 400
trkproperties.geometry.w 400
trkproperties.geometry.x 2
trkproperties.geometry.y 26
```

**Comment by Alexey-Yakovenko** [comment] 2016-02-01 17:23
This config is obviously from 0.6.2, have you tried 0.7.0 yet? The problem might have been fixed already.

**Comment by Lithopsian** [comment] 2016-02-01 23:24
This sounds a bit like playlist column auto-resize going crazy.  I'm not sure what would cause it though.  I copied down this config and it runs fine for me.  Startup timing?  Window geometry on your machine?  Desktop manager?

I did notice the notify bubble opening with no text (just an icon in the bubble) at startup with this config.  It is fine on a track change with Deadbeef already running.

**Comment by ufovsalien** [comment] 2016-02-02 06:01
>Startup timing? Window geometry on your machine? Desktop manager?
Usually it happens on 2-50 album (I restart deadbeef only sometimes), but with one creative commons song and fast deadbeef open/close, I was able to reproduce issue quite quickly. 
>Window geometry on your machine? Desktop manager?
FullHD, gnome-flashback
As example (config by default):
`[{"title":"Cover","id":"8","format":"","size":"200","align":"0","color_override":"0","color":"#ff000000"},{"title":"#","id":"-1","format":"%track%","size":"50","align":"2","color_override":"0","color":"#ff000000"},{"title":"Title","id":"-1","format":"%title%","size":"600","align":"2","color_override":"0","color":"#ff000000"},{"title":"Duration","id":"-1","format":"%playback_time% | %length%","size":"150","align":"2","color_override":"0","color":"#ff000000"},{"title":"Codec","id":"-1","format":"%codec%","size":"150","align":"0","color_override":"0","color":"#ff4d4d4d"},{"title":"Samplerate","id":"-1","format":"%samplerate%","size":"150","align":"0","color_override":"0","color":"#ff4d4d4d"}]`
changes to (issue):
`[{"title":"Cover","id":"8","format":"","size":"771","align":"0","color_override":"0","color":"#ff000000"},{"title":"#","id":"-1","format":"%track%","size":"193","align":"2","color_override":"0","color":"#ff000000"},{"title":"Title","id":"-1","format":"%title%","size":"2312","align":"2","color_override":"0","color":"#ff000000"},{"title":"Duration","id":"-1","format":"%playback_time% | %length%","size":"578","align":"2","color_override":"0","color":"#ff000000"},{"title":"Codec","id":"-1","format":"%codec%","size":"578","align":"0","color_override":"0","color":"#ff4d4d4d"},{"title":"Samplerate","id":"-1","format":"%samplerate%","size":"578","align":"0","color_override":"0","color":"#ff4d4d4d"}]`
Every time this issue happens value in all columns change slightly different but its near 770-778 px in cover section.
I recorded video to show issue in action:
https://dropfile.to/19EOl

**Comment by cboxdoerfer** [comment] 2016-02-02 06:11
I can reproduce that with build from master.

**Comment by cboxdoerfer** [comment] 2016-02-02 06:14
Seems like deadbeef gets initialized with a huge geometry when its launched maximised in gnome shell (and maybe other composited window managers).

**Comment by cboxdoerfer** [comment] 2016-02-04 09:25
Ok, I think what's happening here is this:

Before the gtk mainloop runs we setup the window (gtk_window_move, gtk_window_resize, gtk_window_maximize) in wingeom_restore, those actions get queued and are applied at some point in the gtk mainloop. When they are applied each of them causes a configure event.

Now there is a chance that when some of those configure events fire the listview is already setup and handles one ore more of these events, in which we setup the autoresize values. And here is the problem: The gtk window might not have restored its size yet and the listview has a different width than it had during shutdown the last time. But the column widths belong to a maximized window, so we calculate wrong autoresize values and when the window then gets maximized we stretch or shrink the columns based on wrong values.

I guess a fix is pretty simple: We also have to store the width of the playlist widget in the config, so we can init the autoresize values correctly before the window is even shown. Or does anyone have another idea? @Alexey-Yakovenko @Lithopsian ?

**Comment by Alexey-Yakovenko** [comment] 2016-02-04 09:29
Another idea: send a fake signal through GTK mainloop, that says "now it's safe to apply autoresizing" -- send it after all those configure-spawning things. I think calling `g_idle_add` is enough, after calling the `gtk_widget_show (mainwin)`.

**Comment by cboxdoerfer** [comment] 2016-02-04 09:31
Oh btw. this would also fix the rare case, when the width in maximized mode changed while deadbeef was not running (e.g. different display, user added a dock at the side, tiling wms...)

**Comment by Alexey-Yakovenko** [comment] 2016-02-04 09:35
Yes. Storing the size of playlist view will help for many things. Then doing the "startup finished" signal is not really needed. It would make stuff slightly more predictable, but your approach is more robust.

**Comment by Lithopsian** [comment] 2016-02-04 12:29
Is this using the new autoresize code that I wrote?  I don't think that is in 0.7.  Or doesn't it make any difference?  There is a mechanism for locking the column sizes at startup.  I made this more explicit and later than before, but it is still a bit hopefully just being called from g_idle_add in w_playlist_init in widgets.c.

Knowing the intended size of the playlist would avoid a lot of potential problems.  The new autoresize code explicitly remembers the playlist width for calculating individual column widths, but at startup it is working blind.

**Comment by Alexey-Yakovenko** [comment] 2016-02-04 12:38
> Is this using the new autoresize code that I wrote? I don't think that is in 0.7.

Indeed, it's not in 0.7... can someone check if the same problem happens on master?

Anyway, It's unlikely that we can integrate the fixes from master to 0.7, as they are not independent, and would pull in many unwanted changes.

So we need to come up with another way to fix this.

**Comment by cboxdoerfer** [comment] 2016-02-04 15:37
Yes, bug also happens on master, even a lot worse.

**Comment by cboxdoerfer** [comment] 2016-02-04 15:39
I already have a fix for 0.7, maybe I can modify that (or split it in some parts) so we can use that also on master.

**Comment by Alexey-Yakovenko** [comment] 2016-02-04 15:42
Just do what it takes to fix on 0.7, I'll figure out the master branch when merging. I don't think it will be very complicated.

**Comment by cboxdoerfer** [comment] 2016-02-04 16:29
Do we need to ensure correct auto resizing after a crash? This is the only case where my patch won't work, since the layout and with it the width of the playlist, only gets written on shutdown. Of course fixing that is easy, we just need to save the layout also on most configure events - question is: Do we want that?

**Comment by Alexey-Yakovenko** [comment] 2016-02-04 16:52
Let's start with not doing it, and see what happens. But you raised a good point, and we need to find a way to solve it in a good way.

**Comment by Alexey-Yakovenko** [comment] 2016-02-05 10:31
@ufovsalien please try if this build fixes the problem for you: http://sourceforge.net/projects/deadbeef/files/travis/linux/0.7/deadbeef-static_0.7.1-beta1-1_x86_64.tar.bz2/download

**Comment by ufovsalien** [comment] 2016-02-06 07:01
Segmentation failed with deadbeef-static_0.7.1-beta1-1 build.
```
backtrace() returned 54 addresses
/opt/deadbeef/deadbeef() [0x403a73]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40) [0x7f95ad047d40]
/opt/deadbeef/plugins/ddb_gui_GTK2.so(ddb_listview_build_groups+0x35) [0x7f95acae1da5]
/opt/deadbeef/plugins/ddb_gui_GTK2.so(ddb_listview_update_fonts+0x6f) [0x7f95acae209f]
/opt/deadbeef/plugins/ddb_gui_GTK2.so(ddb_listview_list_configure_event+0x6c) [0x7f95acae21ac]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0x12d815) [0x7f95ac582815]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x138) [0x7f95ab7e83b8]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x21d3d) [0x7f95ab7f9d3d]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xaa9) [0x7f95ab8016f9]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x82) [0x7f95ab801ce2]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0x23d6b4) [0x7f95ac6926b4]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0xb84aa) [0x7f95ac50d4aa]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0xb8585) [0x7f95ac50d585]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x138) [0x7f95ab7e83b8]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x21557) [0x7f95ab7f9557]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xdd9) [0x7f95ab801a29]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x82) [0x7f95ab801ce2]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_widget_realize+0xc0) [0x7f95ac698670]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_widget_map+0xf8) [0x7f95ac698858]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0x82cfa) [0x7f95ac4d7cfa]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0xb50af) [0x7f95ac50a0af]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1055f) [0x7f95ab7e855f]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x438) [0x7f95ab801088]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x82) [0x7f95ab801ce2]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_widget_map+0xce) [0x7f95ac69882e]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0x82cfa) [0x7f95ac4d7cfa]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0xb50af) [0x7f95ac50a0af]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1055f) [0x7f95ab7e855f]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x438) [0x7f95ab801088]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x82) [0x7f95ab801ce2]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_widget_map+0xce) [0x7f95ac69882e]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0x1af1d8) [0x7f95ac6041d8]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0xb50af) [0x7f95ac50a0af]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1055f) [0x7f95ab7e855f]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x438) [0x7f95ab801088]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x82) [0x7f95ab801ce2]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_widget_map+0xce) [0x7f95ac69882e]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0xb50af) [0x7f95ac50a0af]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0xcaffb) [0x7f95ac51fffb]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x105e7) [0x7f95ab7e85e7]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x438) [0x7f95ab801088]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x82) [0x7f95ab801ce2]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_widget_map+0xce) [0x7f95ac69882e]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x105e7) [0x7f95ab7e85e7]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x438) [0x7f95ab801088]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x82) [0x7f95ab801ce2]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_widget_show+0x86) [0x7f95ac697df6]
/opt/deadbeef/plugins/ddb_gui_GTK2.so(w_append+0x3c) [0x7f95acb03eac]
/opt/deadbeef/plugins/ddb_gui_GTK2.so(+0x3117a) [0x7f95acac317a]
/opt/deadbeef/plugins/ddb_gui_GTK2.so(gtkui_thread+0x68f) [0x7f95acac593f]
/opt/deadbeef/plugins/ddb_gui_GTK2.so(+0x33c3c) [0x7f95acac5c3c]
/opt/deadbeef/deadbeef() [0x40351c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f95ad032ec5]
/opt/deadbeef/deadbeef() [0x403985]
```
I back to 12 days old build from drone.io

**Comment by cboxdoerfer** [comment] 2016-02-06 09:59
Yes, I can reproduce that. Will be fixed.

**Comment by cboxdoerfer** [comment] 2016-02-06 10:36
@ufovsalien the crash should be fixed now on newest builds.

**Comment by Alexey-Yakovenko** [comment] 2016-02-06 10:39
@ufovsalien another note: we have migrated from drone.io to travis-ci (only for the player itself for now, but not the plugins builder yet). the builds are always here: https://sourceforge.net/projects/deadbeef/files/travis/

**Comment by cboxdoerfer** [comment] 2016-02-06 10:57
oh and btw. the fix for the autoresizing depends on a new config entry, so the first time you launch deadbeef with the new build the bug still might show up, but from then on it should work fine.

**Comment by ufovsalien** [comment] 2016-02-06 14:03
We could close this bug. Thanks for best support.

**Comment by ufovsalien** [comment] 2016-02-11 16:02
I rebuilded deadbeef myself today (https://launchpad.net/~hda-me/+archive/ubuntu/deadbeef-master). Still no success.

**Comment by cboxdoerfer** [comment] 2016-02-11 16:36
Did you build deadbeef from master branch? Because this won't work, the patch is in 0.7 branch.

**Comment by cboxdoerfer** [comment] 2016-02-11 16:48
The auto resizing in master got refactored an needs a different patch.

**Comment by ufovsalien** [comment] 2016-02-12 06:42
@cboxdoerfer Will try 0.7 branch today.

**Comment by ufovsalien** [comment] 2016-02-12 13:56
Tested. No issue in 0.7 branch.
P.S.: Thanks for best player.

**Comment by Alexey-Yakovenko** [comment] 2016-03-09 12:59
Master has the fix now, therefore closing the bug. Please let me know if it's still broken. I tested and it works for me.

**Closed by Alexey-Yakovenko** 2016-03-09 12:59 UTC
Labels: bug, GTKUI

**Comment by Hasshu** [comment] 2020-06-04 13:31
Looks like I'm encountering this issue with the portable build of DeaDBeeF v1.8.3 (GTK3): the playlist columns get stretched horizontally, which makes the playlist around 30 times wider than the screen resolution.

That's on KDE Plasma 5.18.5.

**Comment by Alexey-Yakovenko** [comment] 2020-06-04 14:06
@Hasshu 
Please create a new issue. It is probably something else than what got fixed in 2016.
Remember to provide the details, like which plugins you have installed, and how you have the UI configured.

**Comment by Hasshu** [comment] 2020-06-06 10:09
@Alexey-Yakovenko Oddly enough, I can't seem to reproduce that after reinstalling (or, rather, re-unpacking) and purging the config folder. Looks like it needs further testing.
