### ISSUE TITLE
Embedded CUE sheets in FLAC files not handled correctly

### ISSUE THREAD

**Issue by asmian** [Alexey-Yakovenko/deadbeef#1523] opened 2016-03-29 16:13 UTC
This issue is related to the media library enhancement request already submitted, but hinges on a bug hence the separate report. Background: I am a Win7/foobar2000 user looking to move to Linux. So far deadbeef is the least sucky replacement for foobar I've found for Linux, by a long way. Most of the issues for me are poor interface design (which unfortunately all the Linux media players seem to be copying from each other), especially round the way they ALL seem to mishandle embedded cue sheets in FLAC files, which is my preferred media form.

The fundamental problem is that all the media players I've tried handle FLAC files as if they only ever contain one track per file, and ignore or misread embedded cue sheets that list subtracks. I rip/store albums as a single FLAC file with EAC, embedding a subtrack cue sheet correctly with album art. One album - one file. That's the correct way. Gapless play, tracks lead seamlessly one to another and there's no wasted disk overhead due to thousands of small files. That's the way most albums were composed by the artists and meant to be heard/played, from start to finish, once upon a time before "pop" degenerated to 3-minute songs with 2 chords, people got miniscule attention spans and discovered shuffle play. The classic example is "Dark Side of the Moon", which apart from a single track used as a single is continuous music through each side of the (old) LP. Each subtrack depends for its impact on its sequence position and the ones around it and was never meant to be heard independently. You'd have thought that with vinyl making a comeback this way of experiencing music had been rediscovered by a new generation... :/

Foobar handles this method of ripping/album play perfectly. You get a proper expandable tree view which lists the albums per your preferred sorting method (eg. using artist/date/album title info from the embedded cue sheets), and by selecting a single *album* and sending to playlist, it plays the album from start to finish, highlighting the correct subtrack, allowing you to change from subtrack to subtrack if you wish, and stops when the album is finished. That respects the album as a single musical entity (with embedded cue points for info).

Just trying deadbeef in its default configuration with albums ripped in this way, the media listing is a huge list with no indentation or grouping, each entry in the list unnecessarily duplicates the album information (author/album column), and there is no date sorting possible. That's an appalling media interface. Hopefully the promised media library enhancement will fix that (plus the ability to custom sort, which isn't documented at all). But the bug is that even when the tracks are listed sequentially the track name info is NOT being pulled from the cue subtracks, it's just duplicating the album name in the track title column. There's no sign of the subtrack title in any playing information, and because everything is single-track-focused rather than respecting the album grouping as a distinct entity, there's no way to send a single *album* to the playlist without manually selecting all the subtracks. Sending the first track does play them sequentially if they are listed that way, but it doesn't stop at the end of the album track listings but goes on to the next album/artist entry, as if the media list is a huge playlist.

Right now I'm giving up on Linux as a place to play my media library. I'm sure if I wasted enough personal time tweaking and trying plugins, or writing my own, I'd get some of the functionality that's missing. Don't worry, due to similar dubious interface issues across much of the alternative software I'm comparing, it's not the only deal-breaker stopping my Linux migration. But I'm incredulous that *none* of the media players I can find handle this cue-sheet subtrack embedding properly, despite foobar (the apparent inspiration for many) handling it perfectly. That's why I'm dropping this here as a bug report so that maybe at least one can get it right for the future - and so you can maybe think about how to handle albums as entities rather than just single tracks, for those who want to listen to them the way they were originally meant to be heard. I hope you do, since deadbeef has the most potential AFAICT as an audiophile player out of the alternatives.

Of course, if someone knows of a Linux player that works correctly in the way I've outlined, do please link me to it!

**Comment by Alexey-Yakovenko** [comment] 2016-03-29 17:41
wow. any chance that you'd provide some TL;DR for those of us who are too busy to read this?

**Comment by Serranya** [comment] 2016-03-29 17:53
> but it doesn't stop at the end of the album track listings but goes on to the next album/artist entry, as if the media list is a huge playlist.

Just select Playback -> Stop after current album

**Comment by asmian** [comment] 2016-03-29 23:30
> Just select Playback -> Stop after current album

Because we don't want our computers to do any simple *automation*, right? (/sarcasm) You have an off switch on your kettle same as me, but I imagine you still expect it to turn *itself* off after boiling water. Like stopping playing at the end of a unit of songs that are defined clearly in the file itself... if you can send the album as a single unit to the playlist (rather than a manually selected set of tracks), then that's what it should play, and nothing more.

Alexey: if you're too busy to read a bug report and therefore understand why this is an issue, then I don't hold out much hope of you fixing it, which is a shame. I tried to give you context so you could understand why people might listen to music in different ways, since every Linux player I've tried seems to assume that there's no interest in playing anything other than single tracks arbitrarily grouped into a playlist. I'm saying that embedding a CUE sheet inside a FLAC that has subtracks IS a playlist. A playlist for an album. So sending the album to playlist should just play the album, from start to finish, and nothing else, as per the embedded CUE sheet. That's a suggestion for an enhancement in your interface that would improve its audiophile credentials. But you need to recognise and implement the idea of sending an album *entity* as well as single/multiple tracks.

The bug connected with this is that when there are multiple tracks in a CUE sheet, you are not extracting, displaying or handling correctly the *track* titles. Eg. for a whole-album FLAC file with this cuesheet:

REM GENRE "Progressive Rock"
REM DATE 1973
PERFORMER "Pink Floyd"
TITLE "Dark Side of the Moon"
FILE "DarkSide.wav" WAVE
  TRACK 01 AUDIO
    TITLE "Speak To Me"
    INDEX 01 0:00:00
  TRACK 02 AUDIO
    TITLE "Breathe"
    INDEX 01 1:07:13
  TRACK 03 AUDIO
    TITLE "On the Run"
    INDEX 01 3:56:53
... etc.

In your media listing, using deadbeef as default installed, the column for "artist/album" is correct, but in the "title" column you repeat the *album* title, NOT the track title, for every subtrack, despite every line entry being one of those separate subtracks which you've correctly extracted from the cuesheet. Your listing contains multiple "Dark Side of the Moon" track names instead of "Speak To Me", then "Breathe", then "On the Run", etc.. I imagine you're parsing the CUE for "TITLE", but you're stopping at the first one it finds (album), not going on to find the matching title for the track you're listing. Perhaps whoever designed this CUE format is at fault for using the same name for both entries. Maybe a plug-in does this properly, but it's bugged as installed out-of-the-box.

Additionally, I'd strongly suggest as an interface improvement to support this, to somehow group album entries together and offset them, or back-colour them, to separate them in the listing without duplicating artist/album names one after another. That's text overload, bad design and doesn't help people find relevant info in a huge list. Having a single title for an associated group of info is much clearer (like a tree list with album nodes). But you seem to be on this track from another bug report I read in which you said you were implementing proper media library handling. Let's hope. ;)

I'm trying to help. If I didn't think deadbeef was well worth pursuing by me in the long term, I wouldn't have bothered making the bug report. But sometimes to explain why something is better (or worse) takes words - I tried to attach a helpful screenshot here (supposedly you can attach files) but the site barfed on it. I'm sorry if that non-trivial detail doesn't suit your attention span.  :(

**Comment by cboxdoerfer** [comment] 2016-03-30 08:38
> Additionally, I'd strongly suggest as an interface improvement to support this, to somehow group album entries together and offset them, or back-colour them, to separate them in the listing without duplicating artist/album names one after another.

Right click on playlist columns -> Group by -> ...

> if you can send the album as a single unit to the playlist (rather than a manually selected set of tracks), then that's what it should play, and nothing more.

Then just add that album to a single playlist, just like foobar2000 does. If you add other tracks to that playlist both foobar2000 and deadbeef will play them, because that's the point of a playlist -> a list containing all tracks to be played.

And if you like to have lots of albums in a playlist, but only want to play one album `Playback -> Stop after current album` is exactly what you are looking for.

> Because we don't want our computers to do any simple automation, right? 

And how exactly should deadbeef or foobar2000 now in advance which tracks of a playlist you want to be played?

Regarding the CUE Sheet issues. Can you provide a CUE sheet that causes this problem?

**Comment by cboxdoerfer** [comment] 2016-03-30 09:02
So I just tried it with an album of mine:

Here's the CUE Sheet:
REM GENRE Progressive Rock
REM DATE 2000 05 23
PERFORMER "A Perfect Circle"
TITLE "Mer de Noms"
FILE "CDImage.wav" WAVE
  TRACK 01 AUDIO
    TITLE "The Hollow"
    PERFORMER "A Perfect Circle"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Magdalena"
    PERFORMER "A Perfect Circle"
    INDEX 01 02:58:72
  TRACK 03 AUDIO
    TITLE "Rose"
    PERFORMER "A Perfect Circle"
    INDEX 01 07:05:02
  TRACK 04 AUDIO
    TITLE "Judith"
    PERFORMER "A Perfect Circle"
    INDEX 01 10:31:00

And this is how this flac file looks in deadbeef:

![](http://i.imgur.com/McMCfwi.png)

**Comment by cboxdoerfer** [comment] 2016-03-30 09:08
In short: I can't reproduce your bug

**Comment by Alexey-Yakovenko** [comment] 2016-03-30 10:24
I read as much as I could from description, and could not find any useful information about what the issue is, and how to reproduce it. Closing.

**Closed by Alexey-Yakovenko** 2016-03-30 10:24 UTC

**Comment by Alexey-Yakovenko** [comment] 2016-03-30 10:27
@asmian after digging through your posts, I found that you mentioned an issue with cuesheet parser, which displays the top level title in every track's title. This sounds like a bug. I'm not asking you to report this as another bug (please don't!), but I will check if this bug is valid anyway.

**Comment by Alexey-Yakovenko** [comment] 2016-03-30 11:01
@asmian checked your cuesheet snippet (the one about `TITLE "Dark Side of the Moon"`). It works correctly, the album title doesn't get duplicated in song titles. I understand it's irrelevant to you, because you switched to Windows, so just FYI: none of the problems you described seem to be valid.

**Comment by jiri-novak-cz** [comment] 2017-05-19 20:01
Maybe closed but still valid. FLAC files with embedded CUE sheet not handled cerrectly. Individual tracks are not being displayed at all.

**Comment by Alexey-Yakovenko** [comment] 2017-05-19 20:07
@jiri-novak-cz please file a new bug report, and attach the cuesheet in question. Remember to specify which deadbeef version you're using.
