### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by Shadowdodger** [Alexey-Yakovenko/deadbeef#1674] opened 2016-11-17 19:32 UTC
![selection_001](https://cloud.githubusercontent.com/assets/23530533/20404159/fe6a4342-ad03-11e6-8439-18c5ba8d3198.png)
Hello! I'm using Antergos KDE and I've recently downgraded GTK 3.22 to 3.20 and gtk-update-icon-cache thinking that it would fix the missing icons for playback control. I'm using a GTK2 GUI Plugin and I've tried changing it to GTK3, but that didn't solve the problem I'm having either. Given that I've recently reinstalled my OS, I'm not aware of how many .20 packages got updated to .22 that could've caused this to happen. Is there a list of packages that affect Deadbeef I can downgrade to fix this or is an update required?

**Comment by Alexey-Yakovenko** [comment] 2016-11-17 19:36
You need to install and configure any icon theme. The standard one is called "hicolor-icon-theme". Right now it looks like no theme is present, or it's misconfigured.

**Comment by Shadowdodger** [comment] 2016-11-17 19:50
![selection_002](https://cloud.githubusercontent.com/assets/23530533/20404955/56dde558-ad07-11e6-8e6a-77cb3945efc6.png)
![selection_003](https://cloud.githubusercontent.com/assets/23530533/20404970/62249db2-ad07-11e6-83da-a061b8c208c7.png)
What do I have to do now?

**Comment by Alexey-Yakovenko** [comment] 2016-11-17 19:51
I'm not familiar with KDE, sorry. Deadbeef is using GTK.

**Comment by Shadowdodger** [comment] 2016-11-17 19:52
Could you contact some contributors that could assist me? I'm sure I'm not the only one having this problems.

**Comment by Alexey-Yakovenko** [comment] 2016-11-17 19:55
Why me? It's a local problem on your computer with some icons in KDE. It doesn't have anything to do with deadbeef in particular. Maybe try rebooting a computer or something.

**Comment by Alexey-Yakovenko** [comment] 2016-11-17 19:59
If you mean contributors of this project -- I think they all read the emails.

**Comment by Alexey-Yakovenko** [comment] 2016-11-18 06:54
@Shadowdodger I just re-read your request, It's not very clear when the problem occured -- after you installed your linux distro, or after you downgraded GTK, or after you did something else.

Please update the report with more clear instructions about how to reproduce the problem.

Please remember to specify which Linux Distribution / version are you using, which deadbeef version, how exacty did you install deadbeef, and whether the official build of deadbeef has the same problem.

It's also important to specify whether the UI worked correctly at all at any point, on the same linux distro, and whether any other GTK applications have similar problems with their icons.

Until then, I'm closing the bug as invalid, because nobody would be able to assist you with just the information you provided.

**Closed by Alexey-Yakovenko** 2016-11-18 06:54 UTC
