### ISSUE TITLE
The OSD notification doesn't display the album art

### ISSUE THREAD

**Issue by laichiaheng** [Alexey-Yakovenko/deadbeef#1431] opened 2016-01-01 05:32 UTC
System: elementary OS
DeaDBeeF version: DeaDBeeF devel
GTK3
![2016-01-01 13 29 31](https://cloud.githubusercontent.com/assets/9532105/12069843/2040b138-b08c-11e5-90bf-d0cc1d5e556f.png)

**Comment by Alexey-Yakovenko** [comment] 2016-01-01 12:11
It's not reproducible in ubuntu+unity, so I'm assuming this bug is either caused by something in the filenames, or it's specific to Elementary.

I can't seem to find any way to install elementary on ubuntu.

But you can help to track down the problem, by doing the following things:

* Check whether the same thing works in other DE, e.g. Unity, or XFCE, or GNOME
* Check if the same thing works in Elementary for the english music

This would help to understand where to look further.

**Comment by Lithopsian** [comment] 2016-01-03 12:20
Is this Gala?  Does the icon ever appear, for example on a track change or restart of the same track?  Have you ever had it in Elementary and it has recently disappeared?

There may be an issue with image sizing.    For example, if the image size doesn't exactly match what the bubble needs or is too big.  You can adjust this in the configuration settings for the notify-osd plugin in Deadbeef.

Or the filename is getting mangled.  If it works in English, but not Chinese then that would be a good guess.  Non-English characters in the title and artist tags will likely all get converted to underscores in the cached icon filename, which should produce an image but isn't exactly ideal.

**Comment by Alexey-Yakovenko** [comment] 2016-01-03 12:28
> Non-English characters in the title and artist tags will likely all get converted to underscores in the cached icon filename, which should produce an image but isn't exactly ideal.

this sounds like a serious regression then.

**Comment by Lithopsian** [comment] 2016-01-03 16:16
It actually works reasonably well in practice.  Extended ASCII characters map to values which are treated as negative and so are not converted to underscores.  I don't remember if this is accidental or intentional.  I probably tested it and it worked so that was the way it stayed.

Maybe this could be improved.  Not all ASCII codes above 127 are pretty printable characters, but at least they aren't control codes or things with a special meaning in a file path.

**Comment by Soukyuu** [comment] 2016-01-12 18:26
Why convert the filenames at all? I don't think there is an OS that uses a non-UTF-8 encoding for file names and that deadbeef runs on?

**Comment by Alexey-Yakovenko** [comment] 2016-01-12 18:41
@Soukyuu it's an accident. will be fixed.

**Comment by Alexey-Yakovenko** [comment] 2016-01-12 18:43
wait.. I checked, nothing is converted. It only replaces certain characters with _. Which is not really needed. It doesn't affect unicode (non-ascii) chars.

**Comment by Alexey-Yakovenko** [comment] 2016-01-12 18:55
I removed the escaping code from the artwork plugin.. If someone knows why it was necessary, please let me know. I couldn't come up with any reasons.

Hopefully, it will also fix this issue, but I can't tell.

**Comment by Alexey-Yakovenko** [comment] 2016-01-12 18:55
Closing because the OP is unresponsive.

**Closed by Alexey-Yakovenko** 2016-01-12 18:55 UTC
