### ISSUE TITLE
Tray icon doesn't appear in MATE 1.18

### ISSUE THREAD

**Issue by spvkgn** [Alexey-Yakovenko/deadbeef#1814] opened 2017-06-17 14:54 UTC
Ubuntu 17.04 MATE Desktop 1.18 - не отображается иконка в трее у devel версии. Версия 0.7.2 - отображается. [console output](http://sprunge.us/dXIO)

**Comment by Alexey-Yakovenko** [comment] 2017-06-28 12:57
Corresponding bug in Mate:
https://github.com/mate-desktop/mate-panel/issues/537

And this bug is probably a duplicate of #1606 (despite it not really referencing Mate)

**Closed by Alexey-Yakovenko** 2017-06-28 12:57 UTC
Labels: duplicate

**Comment by Alexey-Yakovenko** [comment] 2017-06-28 13:03
Basically, this is what's going on:

1. devel version got a new plugin, which supports the new status notification protocol.
2. The new MATE (as well as e.g. Unity) advertised that the protocol is there
3. Deadbeef disables the old tray icon, and starts using the new protocol
4. the icon doesn't appear, because the way Deadbeef implements the menu is not compatible with Unity, and apparently MATE, but is compatible with KDE

Temporary workaround: delete the statusnotifier plugin in deadbeef folder.

**Comment by spvkgn** [comment] 2017-06-28 14:03
@Alexey-Yakovenko Thanks for the tip, I did upgrade mate-panel to 1.18.3 and disable KDE Status notifier in settings - the tray icon restored now.
