### ISSUE TITLE
Launching Audio CD directly from command-line?

### ISSUE THREAD

**Issue by cipricus** [Alexey-Yakovenko/deadbeef#1459] opened 2016-01-26 11:07 UTC
Is there a command that can be used to start an Audio CD directly in Deadbeef?

For example, with Audacious and Qmmp, I can use `audacious cdda://` and `qmmp cdda://`.

Is there something similar for Deadbeef?

With that, one can easily start  an Audio CD with a launcher or add an option like 'Play Audio CD with Deadbeef' to a device notifier (e.g.)

**Comment by Alexey-Yakovenko** [comment] 2016-01-26 11:42
I have looked at the code, and it seems possible, but I couldn't figure out the syntax.
@Lithopsian could you help pls? I think you've been the last one touching the code..

**Comment by Lithopsian** [comment] 2016-01-26 12:06
Absolutely, you can do this.  deadbeef all.cda will load all the detectable audio tracks from the first drive found to contain audio optical media into a playlist and start playback.

You can also play individual tracks, for example deadbeef 3.cda.

**Comment by cipricus** [comment] 2016-01-26 12:10
Great! 

`deadbeef all.cda`

**Comment by Alexey-Yakovenko** [comment] 2016-01-26 12:14
Cheers @Lithopsian , I will keep this one open for reference, and will add the information to plugin description.

**Comment by wdlkmpx** [comment] 2016-01-26 19:14
It would be nice if you added code to choose the device. 

An additional [optional] parameter could be used to select it, something like: deadbeef all.cda /dev/sr1

**Comment by Alexey-Yakovenko** [comment] 2016-01-26 19:20
This actually also seems possible. something like `/dev/sr0/all.cda`, but not 100% sure

**Comment by Lithopsian** [comment] 2016-01-26 21:12
Yes, you can specify the device as part of the path if you have more than one drive.

**Comment by wdlkmpx** [comment] 2016-01-26 23:00
I can confirm that # deadbeef /dev/sr1/6.cda plays track 6 from cdaudio inserted in /dev/sr1

There is a discussion about this here:
http://crunchbang.org/forums/viewtopic.php?id=31280

"Many of the things I thought were missing at first glance do seem to be there in obscure corners or plugins.  For example, who knew the command to play whatever is sitting in the first CD drive is "deadbeef all.cda"?  Haven't found any obvious way to play other CD drives yet.  Anyone?"

Here are some other "requests":

- a cdparanoia plugin, so I could use Deadbeef to rip CDs (not exactly a code feature, but it can already rip except only using the standard cdio library so no error correction) ;
- automatic replaygain support in the converter;
- better MP3/MP4 tagging, where "better" means *some*, although in an ideal world I'd rather not have to use that format at all.

**Comment by Lithopsian** [comment] 2016-01-26 23:34
That's funny on so many levels :)  When I wrote that Deadbeef didn't have support for multiple optical drives.  I added it in late 2014 so it should be in 0.6.2, definitely in 0.7.

cdparanoia support is built in to the CDDA plugin.  I'm assuming you have it disabled in your build for some reason.  I thought the default was to build it if the library was available.  Check your configure output and it will tell you (checking for main in -lcdda_paranoia...).  You'll know when you have it because there is a checkbox in the config to disable it.

**Comment by Alexey-Yakovenko** [comment] 2016-01-27 07:55
Yeah, this forum discussion is too old, even from before 0.6.2, and the large changes (cdparanoia etc) were added later than 0.6.2 I believe.

But many of the mentioned things have been added only last year, and will be in 0.7.

**Comment by Lithopsian** [comment] 2016-02-02 21:45
FYI, cdparanoia isn't in the 0.7.0 static build.

**Comment by Alexey-Yakovenko** [comment] 2016-02-03 08:01
thanks, will fix.

**Comment by Alexey-Yakovenko** [comment] 2016-05-04 13:32
I guess that this has been fixed in 0.7.0

**Closed by Alexey-Yakovenko** 2016-05-04 13:32 UTC
