### ISSUE TITLE
Undefined or dead condition

### ISSUE THREAD

**Issue by mmcco** [Alexey-Yakovenko/deadbeef#1491] opened 2016-02-27 00:05 UTC
I'm not sure what [this](https://github.com/Alexey-Yakovenko/deadbeef/blob/master/plugins/ao/eng_dsf/arm7i.c#L1277) is supposed to be - maybe `cpu->kod & (1 << 22)`? In it's current form, it's a constant true expression because there are only two possibilities:

* no overflow
* undefined overflow

And the latter is only possible if you're on a platform with 16-bit ints, which effectively don't exist anymore.

**Comment by Alexey-Yakovenko** [comment] 2016-02-27 08:29
We'll never know...

**Comment by mmcco** [comment] 2016-02-27 20:57
Hm?

**Comment by Alexey-Yakovenko** [comment] 2016-02-29 10:35
What I mean is that unless there's an actual bug associated with this -- nobody will ever look into "fixing" this.

**Comment by mmcco** [comment] 2016-02-29 16:16
Dude, I don't use deadbeef and I don't have an ARM 7 device to test this on anyway. What you have now is a not-so-subtle `if (1) {...} else {...}` bug that is almost definitely the result of a typo. If you don't want to fix it, that's not my problem.

**Comment by Alexey-Yakovenko** [comment] 2016-02-29 16:25
It's a code of ARM7 emulator. You should have more luck if you report this to the developer.
Since this bug report doesn't have any indication of how to reproduce it, or a description what problems does it cause, and there's nobody who knows this code -- I can only close the bug as invalid or wontfix. Sorry.

**Comment by Alexey-Yakovenko** [comment] 2016-02-29 16:29
(or I can keep it open, and hope someone will be interested in figuring it out and fixing it)

**Comment by Alexey-Yakovenko** [comment] 2016-02-29 16:32
It's not that I don't want to fix it. We don't even know if this is a bug for sure.

Oh and btw this code is never used in deadbeef, as it's inside of `#ifdef ARM7_THUMB` block, and we never define ARM7_THUMB

So it's pretty safe to close.

**Closed by Alexey-Yakovenko** 2016-02-29 16:32 UTC
