### ISSUE TITLE
Drop SourceForge

### ISSUE THREAD

**Issue by svnpenn** [Alexey-Yakovenko/deadbeef#1644] opened 2016-09-09 15:51 UTC
This project seems interesting, but I am hesitant to even download the program because of bad reputation of SourceForge. This issue was previously discussed in #1237:

> It had been considered, and refused, because github doesn't provide full replacement of the necessary features. If you're interested in continuing this discussion, please do so in a more appropriate place -- e.g. one of our IRC channels.

I take exceptions to this:

1. IRC is not the correct place for this discussion, http://github.com/Alexey-Yakovenko/deadbeef/issues is

2. This is not possible because the last issue was closed and locked

3. Github does provide full replacement of the necessary features. If not, @Alexey-Yakovenko has failed to explain what those missing features are

**Comment by svnpenn** [comment] 2016-09-09 15:51
https://github.com/Alexey-Yakovenko/deadbeef/issues/1237

**Comment by Alexey-Yakovenko** [comment] 2016-09-09 16:04
duplicate of #1237

**Closed by Alexey-Yakovenko** 2016-09-09 16:04 UTC

**Comment by Alexey-Yakovenko** [comment] 2016-09-09 16:05
I don't need to explain anything. If you interested in a chat about why github is not a replacement for sf.net -- feel free to email me directly. Thanks for understanding.
