### ISSUE TITLE
0.7.2 - Makefile.am warning source file is in a subdirectory...

### ISSUE THREAD

**Issue by Geyup** [Alexey-Yakovenko/deadbeef#1609] opened 2016-07-06 01:08 UTC
In Linux with automake-1.15, when I started to compile 0.7.2, I ended up seeing this message at the terminal;

Makefile.am: installing './INSTALL'
Makefile.am:19: warning: source file 'md5/md5.c' is in a subdirectory,
Makefile.am:19: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
Makefile.am: installing './depcomp'
plugins/adplug/Makefile.am:11: warning: source file 'libbinio/binfile.cpp' is in a subdirectory,
plugins/adplug/Makefile.am:11: but option 'subdir-objects' is disabled
plugins/adplug/Makefile.am:11: warning: source file 'libbinio/binio.cpp' is in a subdirectory,
plugins/adplug/Makefile.am:11: but option 'subdir-objects' is disabled
plugins/adplug/Makefile.am:11: warning: source file 'libbinio/binstr.cpp' is in a subdirectory,
plugins/adplug/Makefile.am:11: but option 'subdir-objects' is disabled

**Comment by Geyup** [comment] 2016-07-06 01:28
Ok I think I have this, I changed the configure.ac to the below;

```AM_INIT_AUTOMAKE([1.11 dist-bzip2 tar-ustar silent-rules subdir-objects])```

Now when I run sh autogen.sh I see this in the terminal;

Running automake...
configure.ac:20: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:20: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:20: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.ac:10: installing './compile'
configure.ac:11: installing './config.guess'
configure.ac:11: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'
Running intltoolize

So is this the correct change, and what now about the ```AM_PROG_MKDIR_P```?

**Comment by Alexey-Yakovenko** [comment] 2016-07-06 06:22
duplicate of: #1157, #1530, #1582

**Closed by Alexey-Yakovenko** 2016-07-06 06:22 UTC
Labels: duplicate

**Comment by Geyup** [comment] 2016-07-08 06:04
Hi,

So for now this is a correct fix?
```AM_INIT_AUTOMAKE([1.11 dist-bzip2 tar-ustar silent-rules subdir-objects])``` 

Thanks

**Comment by Geyup** [comment] 2016-07-08 06:23
Nope changing this, it won't compile it fails.

Not sure if it's related but I get a lot of ```No such file or directory``` in the below path...

Making all in plugins/gme
make[2]: Entering directory '/tmp/sar/deadbeef-0.7.2/plugins/gme'
Makefile:1721: game-music-emu-0.6pre/gme/.deps/Ay_Apu.Plo: No such file or directory
Makefile:1722: game-music-emu-0.6pre/gme/.deps/Ay_Core.Plo: No such file or directory
Makefile:1723: game-music-emu-0.6pre/gme/.deps/Ay_Cpu.Plo: No such file or directory

And then the compile fails;

make[2]: *** No rule to make target 'game-music-emu-0.6pre/vgmplay/VGMPlay/chips/.deps/ymz280b.Plo'.  Stop.
make[2]: Leaving directory '/tmp/foo/deadbeef-0.7.2/plugins/gme'
Makefile:873: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/sar/deadbeef-0.7.2'
Makefile:619: recipe for target 'all' failed
make: *** [all] Error 2

Is warning: source file is in a subdirectory a problem to compile it like this, or it needs to be fixed?

**Comment by Alexey-Yakovenko** [comment] 2016-07-08 06:52
@Geyup  The same question has already been asked in at least one of the 3 issues that I linked above. I don't think anyone came up with the fix for this problem so you have a possibility to be the first! Good luck!

**Comment by Geyup** [comment] 2016-07-09 01:02
I changed back

AM_INIT_AUTOMAKE([1.11 dist-bzip2 tar-ustar silent-rules])

And it compiles and runs just fine, so it seems ok for now.

I'll see if I can help figure it out...

thanks
