### ISSUE TITLE
Segmentation Fault artwork

### ISSUE THREAD

**Issue by midyukov-anton** [Alexey-Yakovenko/deadbeef#1551] opened 2016-04-21 05:42 UTC
selected output plugin: PulseAudio output plugin
INFO: loading playlist Плейлист
INFO: from file /home/anton/.config/deadbeef/playlists/0.dbpl
plugin VKontakte failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.20.3
connecting button tray signals
Cannot create status notifier, falling back to GtkStatusIcon
Segmentation Fault
backtrace() returned 10 addresses
deadbeef() [0x403c60]
/lib64/libc.so.6(+0x33400) [0x7f931b034400]
/usr/lib64/deadbeef/artwork.so(mp4ff_read_data+0x10) [0x7f930c700580]
/usr/lib64/deadbeef/artwork.so(mp4ff_atom_read_header+0x36) [0x7f930c700846]
/usr/lib64/deadbeef/artwork.so(+0x8f67) [0x7f930c6fef67]
/usr/lib64/deadbeef/artwork.so(mp4ff_open_read_coveronly+0x2a) [0x7f930c6ff13a]
/usr/lib64/deadbeef/artwork.so(+0x72ed) [0x7f930c6fd2ed]
/usr/lib64/deadbeef/artwork.so(+0x760d) [0x7f930c6fd60d]
/lib64/libpthread.so.0(+0x7434) [0x7f931b3a8434]
/lib64/libc.so.6(clone+0x6d) [0x7f931b0e779d]

I might add that falls while playing the file, if enabled this option here, which I've highlighted in red in the picture. 
That is, the problem in the readout of the tag cover
![2016-04-21 12-18-55](https://cloud.githubusercontent.com/assets/13087750/14699028/81589092-07be-11e6-8f51-7bf439157849.png)

**Comment by Alexey-Yakovenko** [comment] 2016-04-21 07:30
duplicate of #1550

**Closed by Alexey-Yakovenko** 2016-04-21 07:30 UTC
