### ISSUE TITLE
sorting doesn't interpret numbers in the strings

### ISSUE THREAD

**Issue by JulianLai** [Alexey-Yakovenko/deadbeef#1607] opened 2016-07-05 06:30 UTC
![fafsdfsdfdfsdf](https://cloud.githubusercontent.com/assets/20014762/16575727/fef8b548-42bc-11e6-9047-4544d0c37715.png)

The rule of my songlist order:
%album artist% %album% %discnumber% %tracknumber%

Their "album artist" and "album" are the same, so they should be ordered by the "disc number"

**Comment by Alexey-Yakovenko** [comment] 2016-07-05 07:23
Duplicate of #1579

**Comment by Alexey-Yakovenko** [comment] 2016-07-05 07:24
Actually, I'll keep this as a tracking issue, because it has a better summary and screenshot.

**Comment by Alexey-Yakovenko** [comment] 2016-08-01 11:12
After evaluating this issue, I came up with the conclusion, that the best solution to this is title formatting itself.

The sort algorithm should not be trying to be smarter than the user - it doesn't really know the user's intention.

The `%discnumber%` doesn't pad with the disc number with zeroes, which is why it doesn't work, so we need to pad them.

For that, we have the `$num(n,len)`

So your title formatting script needs to use `$num(%discnumber%,2)`.

And as far as I can tell, $num is already implemented.

**Closed by Alexey-Yakovenko** 2016-08-01 11:12 UTC
