### ISSUE TITLE
%playback_time% works every other time when playlist has no focus

### ISSUE THREAD

**Issue by spvkgn** [Alexey-Yakovenko/deadbeef#1481] opened 2016-02-08 15:40 UTC
Seems like a bug. Please see [video](https://drive.google.com/open?id=0B2eWU3wmchq_cmw1YXdBTUZzaUk)

**Comment by Alexey-Yakovenko** [comment] 2016-02-08 15:57
duplicate of #1379

**Closed by Alexey-Yakovenko** 2016-02-08 15:57 UTC
Labels: bug, duplicate, GTKUI, tf
