### ISSUE TITLE
Make Column Headers Alignment also Left, Right, or Center

### ISSUE THREAD

**Issue by rmlrml** [Alexey-Yakovenko/deadbeef#1721] opened 2017-03-06 20:34 UTC
Feature Request: Make Column Header alignment match the alignment of the rest of the column text according to the Edit Column: Alignment (Left, Right, or Center) setting.  I think it would keep things more visually trackable and cleaner looking.

**Comment by Alexey-Yakovenko** [comment] 2017-03-07 13:05
duplicate of #680

**Closed by Alexey-Yakovenko** 2017-03-07 13:05 UTC
Labels: duplicate
