### ISSUE TITLE
DeaDBeeF doesn't show its tray icon

### ISSUE THREAD

**Issue by TotalCaesar659** [Alexey-Yakovenko/deadbeef#1845] opened 2017-08-09 16:26 UTC
### What's going on? Describe the problem in as much detail as possible.
After checking latest master build, I saw casually that there is no tray icon (the option is enabled by default). To be precise, when starting DeadBeeF, tray icon appears for a small time and disappears.
I tried to launch it in terminal, and it shoed me this one:

> gtkui plugin compiled for gtk version: 3.10.8
> 
> ** (deadbeef:11108): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
> connecting button tray signals
> 
> (deadbeef:11108): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()
> 
> (deadbeef:11108): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()
> 
> (deadbeef:11108): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()
> 
> (deadbeef:11108): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()
> 
> (deadbeef:11108): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

### Information about the software:
Deadbeef version: latest master build
OS: Lubuntu 16.04.3

**Comment by Alexey-Yakovenko** [comment] 2017-08-09 16:48
that's interesting.. do you have any tracks in the playlist whose tags were not correctly recoded into utf8?

**Comment by TotalCaesar659** [comment] 2017-08-09 18:08
Yeah, I've launched it with playlist before, but I removed config folder and started it again. Same result with no tray icon.
Full output:

> starting deadbeef devel [static] [portable]
> installdir: /home/max/Downloads/1/deadbeef-devel
> confdir: /home/max/.config
> docdir: /home/max/Downloads/1/deadbeef-devel/doc
> plugindir: /home/max/Downloads/1/deadbeef-devel/plugins
> pixmapdir: /home/max/Downloads/1/deadbeef-devel/pixmaps
> server_start
> INFO: unlink socket: Нет такого файла или каталога
> searching for GUI plugins in /home/max/.local/lib64/deadbeef
> searching for GUI plugins in /home/max/.local/lib/deadbeef
> searching for GUI plugins in /home/max/Downloads/1/deadbeef-devel/plugins
> load_plugin_dir /home/max/Downloads/1/deadbeef-devel/plugins: scandir found 53 files
> found gui plugin ddb_gui_GTK2.so
> added GTK2 gui plugin
> found gui plugin ddb_gui_GTK3.so
> added GTK3 gui plugin
> load gui plugin
> checking GUI plugin: GTK2
> found selected GUI plugin: GTK2
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/ddb_gui_GTK2.so
> loading plugins from /home/max/.local/lib64/deadbeef
> loading plugins from /home/max/.local/lib/deadbeef
> loading plugins from /home/max/Downloads/1/deadbeef-devel/plugins
> load_plugin_dir /home/max/Downloads/1/deadbeef-devel/plugins: scandir found 53 files
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/aac.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/adplug.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/alac.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/alsa.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/artwork.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/cdda.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/converter.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/converter_gtk2.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/converter_gtk3.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/dca.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/ddb_dumb.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/ddb_mono2stereo.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/ddb_shn.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/dsp_libsrc.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/ffap.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/ffmpeg.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/flac.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/gme.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/hotkeys.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/in_sc68.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/lastfm.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/m3u.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/mms.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/mp3.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/musepack.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/notify.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/nullout.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/oss.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/pltbrowser_gtk2.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/pltbrowser_gtk3.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/psf.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/pulse.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/shellexec.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/shellexecui_gtk2.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/shellexecui_gtk3.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/sid.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/sndfile.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/statusnotifier.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/supereq.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/tta.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/vfs_curl.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/vfs_zip.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/vorbis.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/vtx.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/wavpack.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/wildmidi.so
> loading plugin /home/max/Downloads/1/deadbeef-devel/plugins/wma.so
> selected output plugin: ALSA output plugin
> plt_load: failed to open /home/max/.config/deadbeef/default.dbpl
> convgui: gtkui plugin not found
> plugin Converter GTK3 UI failed to connect to dependencies, deactivated.
> plugin Playlist browser GTK3 failed to connect to dependencies, deactivated.
> shellexecui: can't find gtkui plugin
> plugin Shellexec GTK3 UI failed to connect to dependencies, deactivated.
> resume: track -1 pos -1.000000 playlist -1
> gtkui plugin compiled for gtk version: 2.16.0
> connecting button tray signals

**Comment by Alexey-Yakovenko** [comment] 2017-08-10 07:11
What happens if you delete `statusnotifier.so`? Better or worse?

**Comment by Alexey-Yakovenko** [comment] 2017-08-10 08:35
Can you verify if deadbeef 0.7.2 exposes the same behavior? I'm trying to find what to blame, deadbeef or ubuntu. I can't remember anything systray-related being changed recently in deadbeef.

**Comment by Alexey-Yakovenko** [comment] 2017-08-10 08:40
closing as duplicate of #1608, unless proven otherwise

**Closed by Alexey-Yakovenko** 2017-08-10 08:40 UTC
Labels: bug

**Comment by TotalCaesar659** [comment] 2017-08-10 11:20
DeaDBeeF 0.7.2 works normally, problem is in master build only.

**Comment by Alexey-Yakovenko** [comment] 2017-08-10 11:31
ok. Please see the other messages, and the issue #1608 -- they cover the issue in a lot of details. Deleting statusnotifier plugin should solve your problem, until we get it sorted properly.

**Comment by TotalCaesar659** [comment] 2017-08-10 12:15
Yeah, deleting statusnotifier.so works, thanks. I hope you'll solve it.
