### ISSUE TITLE
Playing music causes lag in a video game

### ISSUE THREAD

**Issue by notexe** [Alexey-Yakovenko/deadbeef#1829] opened 2017-07-02 12:16 UTC
This is happening when I am playing Minecraft.

**### Steps to reproduce the problem**
1. Play a video game (Might affect Minecraft only).
2. Play music.

**### What's going on? Describe the problem in as much detail as possible.**
Significant lag in-game caused by deadbeef when playing audio. I have used VLC to play the exact same song and I did not get any performance drops, so it's not an issue with my hardware being too old or anything.

**Deadbeef version:** 0.7.2
**OS:** Arch Linux (4.11.7-1-ARCH)

**Comment by Alexey-Yakovenko** [comment] 2017-07-02 15:39
This may be caused by your configuration. I'm not sure what it could be, but ALSA, PulseAudio and Deadbeef itself can be configured top use very CPU-intensive resampling algorithms, which may cause the problems which you experience.

So basically check how much CPU is taken when deadbeef is playing music, and if it's very high -- reset the settings.

**Comment by Alexey-Yakovenko** [comment] 2017-07-02 15:40
Closing the issue, because there's not much I can do with this. It's definitely not a problem with the player in its default configuration.

**Closed by Alexey-Yakovenko** 2017-07-02 15:40 UTC
