### ISSUE TITLE
Directory monitoring

### ISSUE THREAD

**Issue by SamHH** [Alexey-Yakovenko/deadbeef#1197] opened 2015-03-21 23:11 UTC
The ability to add a local directory to be monitored for changes which automatically updates the library would be fantastic, and would save me having to manually remove everything and re-add my /music folder each time I download/rip a load of new music. Most music players support this feature.

**Comment by Alexey-Yakovenko** [comment] 2015-03-22 10:44
duplicate of #654

**Closed by Alexey-Yakovenko** 2015-03-22 10:44 UTC
