### ISSUE TITLE
Replaygain doesn't work

### ISSUE THREAD

**Issue by SoundSonic1** [Alexey-Yakovenko/deadbeef#1685] opened 2016-12-24 22:16 UTC
Hi,
i tried your latest precompiled deadbeef version for Linux on my Arch machine and the replay gain function does
not seem to work. On the 0.7.3-alpha1 version, back from October, replay gain still works.

**Comment by Soukyuu** [comment] 2017-01-01 15:38
Caused by c2bf383d1a3abe196d9ae3d3d77ddb177595ced8
The GTK UI seems to still be using the old RG API, which probably fails with newer builds. 

I also noticed that the GTK UI/linux side is not up to date on some features the cocoaui/OSX now has, for example RG type applied depending on playback mode (handled via plugin at the moment), rg scanner being built-in (no switch to build for GTK UI/linux) etc.

**Comment by Alexey-Yakovenko** [comment] 2017-01-01 15:48
@Soukyuu macOS has been my primary OS for >2 years now. Obviously, that means that new features are being developed on/for macOS first, and then need to be ported to linux. The porting work needs to be done at some point, e.g. right before releasing version 0.8 for linux. But this is not high priority.

**Comment by Soukyuu** [comment] 2017-01-01 15:51
@Alexey-Yakovenko that's what I thought. It would be a pity if deadbeef on linux gets abandoned, but if it's still planned to also implement those features on linux, then I guess all is fine.

**Comment by Alexey-Yakovenko** [comment] 2017-01-02 07:21
@SoundSonic1 can you describe in more detail, how exactly do you identify that replaygain is not working? Any specifics, like which file format has been used? I just tried with MP3, and it seems to work correctly. It's possible though that other formats has regressed, because there's now a separate code path for MP3 replaygain handling.

**Comment by Soukyuu** [comment] 2017-01-02 17:14
Hmm... checked out just now and it still doesn't seem to work for any wv, flac or tak files I tested.
- listen to file without RG tags
- scan files (in foobar2000 for .tak) -> -10dB gain
- make sure deadbeef lists RG tags
- listen again

-> no change in volume 

- go to "Preferences" -> "Playback" while said file is playing
- adjust "w/  RG preamp" slider to -12dB

-> no change

- go to "Preferences" -> "Playback" while said file is playing
- adjust "w/o RG preamp" slider to -12dB

-> volume changes after a few seconds

Tried all three source settings, processing is set to "apply"

**Comment by Alexey-Yakovenko** [comment] 2017-01-02 17:18
@Soukyuu in the build you used, do you see the changes in RG preferences UI compared with the previous build?

**Comment by Soukyuu** [comment] 2017-01-02 17:20
Yes, including the new "source" RG mode

**Comment by Alexey-Yakovenko** [comment] 2017-01-02 17:21
Then I don't know.. Will re-test as soon as possible, but I used the same testing method as you pretty much, except I used deadbeef's own RG-scanner on mac, then copied the resulting file to linux.

**Comment by Soukyuu** [comment] 2017-01-02 17:26
https://dl.dropboxusercontent.com/u/19330332/1.01.%20angela%20-%20%E6%98%8E%E6%97%A5%E3%81%B8%E3%81%AEbrilliant%20road.wv <- does this one work on mac for you?

**Comment by SoundSonic1** [comment] 2017-01-02 17:26
I just recompiled from source and i can confirm replay gain only works on mp3 but not flac files :(

**Comment by Alexey-Yakovenko** [comment] 2017-01-02 17:36
@Soukyuu I'll be able to try this out later, or maybe tomorrow. Will get back as soon as I know more.

**Comment by Alexey-Yakovenko** [comment] 2017-01-02 19:44
> does this one work on mac for you?

Yes, and I tried FLAC as well. (deleting the link to avoid issues)

**Comment by Alexey-Yakovenko** [comment] 2017-01-02 19:54
I will re-check and fix on linux tomorrow, if I'm able to repro

**Comment by Soukyuu** [comment] 2017-01-02 20:03
Good, then at least it's not the file. That's the one I tested with.

**Comment by Alexey-Yakovenko** [comment] 2017-01-03 10:12
It's fixed now. The bug was in the integer volume calculation, but not in the float32 path.

macOS wasn't affected because output is always float32.

**Closed by Alexey-Yakovenko** 2017-01-03 10:12 UTC
Labels: bug
