### ISSUE TITLE
GTKUI layout is lost after upgrading from 0.6.2 to trunk

### ISSUE THREAD

**Issue by Geyup** [Alexey-Yakovenko/deadbeef#1233] opened 2015-07-10 01:02 UTC
I applied the patch and deadbeef compiled ok.

But when I ran it I noticed the layout I created was all gone and there was a message at the terminal;

```** (deadbeef:3281): WARNING **: Widget not found: Skip to_menu```

Should the layout I created in the Stable version 0.6.2, also work in the latest git branch, or I need to recreate it?

Here's the output from the command line;

```
starting deadbeef devel
server_start
searching for GUI plugins in /home/foo/.local/lib64/deadbeef
searching for GUI plugins in /home/foo/.local/lib/deadbeef
load_plugin_dir /home/foo/.local/lib/deadbeef: scandir found 3 files
searching for GUI plugins in /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 50 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /usr/lib64/deadbeef/ddb_gui_GTK2.so
loading plugins from /home/foo/.local/lib64/deadbeef
loading plugins from /home/foo/.local/lib/deadbeef
load_plugin_dir /home/foo/.local/lib/deadbeef: scandir found 3 files
loading plugin /home/foo/.local/lib/deadbeef/ddb_infobar_gtk2.so
loading plugins from /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 50 files
loading plugin /usr/lib64/deadbeef/aac.so
loading plugin /usr/lib64/deadbeef/alsa.so
loading plugin /usr/lib64/deadbeef/artwork.so
loading plugin /usr/lib64/deadbeef/cdda.so
loading plugin /usr/lib64/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib64/deadbeef/flac.so
loading plugin /usr/lib64/deadbeef/hotkeys.so
loading plugin /usr/lib64/deadbeef/m3u.so
loading plugin /usr/lib64/deadbeef/mp3.so
loading plugin /usr/lib64/deadbeef/nullout.so
loading plugin /usr/lib64/deadbeef/oss.so
loading plugin /usr/lib64/deadbeef/sndfile.so
loading plugin /usr/lib64/deadbeef/supereq.so
loading plugin /usr/lib64/deadbeef/vfs_curl.so
loading plugin /usr/lib64/deadbeef/vorbis.so
selected output plugin: ALSA output plugin
INFO: loading playlist My Music
INFO: from file /home/foo/.config/deadbeef/playlists/0.dbpl
INFO: loading playlist My Music
INFO: from file /home/foo/.config/deadbeef/playlists/1.dbpl
gtkui plugin compiled for gtk version: 2.24.20
connecting button tray signals

** (deadbeef:3281): WARNING **: Widget not found: Skip to_menu
quitting gtk
gtkui_stop completed
gui plugin has quit; waiting for mainloop thread to finish
plug_disconnect_all
plug_unload_all
stopping GTK2 user interface...
quitting gtk
stopping ALSA output plugin...
stopping Album Artwork...
stopping Hotkey manager...
stopping Null output plugin...
stopping OSS output plugin...
stopping WAV/PCM player...
stopping SuperEQ...
stopping cURL vfs...
stopping OggVorbis decoder...
stopped all plugins
all plugins had been unloaded
messagepump_free
plug_cleanup
hej-hej!
```

**Comment by Alexey-Yakovenko** [comment] 2015-07-10 07:36
Sorry for editing your bug description, I don't want to have the unrelated bugs linked together.

**Comment by Geyup** [comment] 2015-07-10 08:52
Hi,

No problem for edit. :)

Ok layout not working...

Please let me know when ready to test again?

**Comment by Alexey-Yakovenko** [comment] 2015-07-10 09:38
ok, I just tried this:

1. downloaded, unpacked deadbeef 0.6.2, launched it, edited layout, quit
2. ran latest git build
3. edited layout in the git build, quit
4. ran 0.6.2 again
5. the layout survived going all the way through from 0.6.2 to latest and back, with edits.

I'm closing this issue since I can't reproduce it.

If you find a way to reproduce the problem -- I will be happy to fix.

**Closed by Alexey-Yakovenko** 2015-07-10 09:38 UTC
Labels: bug

**Comment by cboxdoerfer** [comment] 2015-07-10 15:10
Just for reference:
```** (deadbeef:3281): WARNING **: Widget not found: Skip to_menu```

That's caused by this line https://github.com/Alexey-Yakovenko/deadbeef/blob/master/plugins/gtkui/actions.c#L164 and is totally harmless.

**Comment by Geyup** [comment] 2015-07-10 23:32
I compiled 0.6.2 from source;

http://sourceforge.net/projects/deadbeef/files/deadbeef-0.6.2.tar.bz2/download

Have any of the compile/flag options changed from 0.6.2 to the latest git version?

These are my compile options I have been using;

```
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --disable-adplug \
  --disable-alac \
  --disable-converter \
  --disable-dca \
  --disable-dumb \
  --disable-ffap \
  --disable-ffmpeg \
  --disable-gme \
  --disable-gtk3 \
  --disable-lfm \
  --disable-mms \
  --disable-musepack \
  --disable-nls \
  --disable-notify \
  --disable-pltbrowser \
  --disable-psf \
  --disable-pulse \
  --disable-shellexec \
  --disable-shn \
  --disable-sid \
  --disable-src \
  --disable-tta \
  --disable-vfs-zip \
  --disable-vtx \
  --disable-wavpack \
  --disable-wildmidi \
  --disable-sc68 \
  --disable-wma \
  --enable-shared \
  --build=$ARCH-slackware-linux
```

I am getting the same problem again, here's the output from the terminal

```
starting deadbeef devel
server_start
searching for GUI plugins in /home/foo/.local/lib64/deadbeef
searching for GUI plugins in /home/foo/.local/lib/deadbeef
load_plugin_dir /home/foo/.local/lib/deadbeef: scandir found 3 files
searching for GUI plugins in /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 50 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /usr/lib64/deadbeef/ddb_gui_GTK2.so
loading plugins from /home/foo/.local/lib64/deadbeef
loading plugins from /home/foo/.local/lib/deadbeef
load_plugin_dir /home/foo/.local/lib/deadbeef: scandir found 3 files
loading plugin /home/foo/.local/lib/deadbeef/ddb_infobar_gtk2.so
loading plugins from /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 50 files
loading plugin /usr/lib64/deadbeef/aac.so
loading plugin /usr/lib64/deadbeef/alsa.so
loading plugin /usr/lib64/deadbeef/artwork.so
loading plugin /usr/lib64/deadbeef/cdda.so
loading plugin /usr/lib64/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib64/deadbeef/flac.so
loading plugin /usr/lib64/deadbeef/hotkeys.so
loading plugin /usr/lib64/deadbeef/m3u.so
loading plugin /usr/lib64/deadbeef/mp3.so
loading plugin /usr/lib64/deadbeef/nullout.so
loading plugin /usr/lib64/deadbeef/oss.so
loading plugin /usr/lib64/deadbeef/sndfile.so
loading plugin /usr/lib64/deadbeef/supereq.so
loading plugin /usr/lib64/deadbeef/vfs_curl.so
loading plugin /usr/lib64/deadbeef/vorbis.so
selected output plugin: ALSA output plugin
INFO: loading playlist My Music
INFO: from file /home/foo/.config/deadbeef/playlists/0.dbpl
INFO: loading playlist My Music
INFO: from file /home/foo/.config/deadbeef/playlists/1.dbpl
gtkui plugin compiled for gtk version: 2.24.20
connecting button tray signals

** (deadbeef:29278): WARNING **: Widget not found: Skip to_menu
quitting gtk
gtkui_stop completed
gui plugin has quit; waiting for mainloop thread to finish
plug_disconnect_all
plug_unload_all
stopping GTK2 user interface...
quitting gtk
stopping ALSA output plugin...
stopping Album Artwork...
stopping Hotkey manager...
stopping Null output plugin...
stopping OSS output plugin...
stopping WAV/PCM player...
stopping SuperEQ...
stopping cURL vfs...
stopping OggVorbis decoder...
stopped all plugins
all plugins had been unloaded
messagepump_free
plug_cleanup
hej-hej!
```

**Comment by Geyup** [comment] 2015-07-11 00:03
I went back and double checked the stable 0.6.2 source, since I updated to glib2-2.42.2 and applied the patch I showed you, and it's working ok.

I only have a problem with the git version... hmm

Here's the output from 0.6.2 stable;

```
starting deadbeef 0.6.2
server_start
searching for GUI plugins in /home/foo/.local/lib64/deadbeef
searching for GUI plugins in /home/foo/.local/lib/deadbeef
plug_load_all: scandir found 3 files
searching for GUI plugins in /usr/lib64/deadbeef
plug_load_all: scandir found 50 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /usr/lib64/deadbeef/ddb_gui_GTK2.so
loading plugins from /home/foo/.local/lib64/deadbeef
loading plugins from /home/foo/.local/lib/deadbeef
plug_load_all: scandir found 3 files
loading plugin /home/foo/.local/lib/deadbeef/ddb_infobar_gtk2.so
loading plugins from /usr/lib64/deadbeef
plug_load_all: scandir found 50 files
loading plugin /usr/lib64/deadbeef/aac.so
loading plugin /usr/lib64/deadbeef/alsa.so
loading plugin /usr/lib64/deadbeef/artwork.so
loading plugin /usr/lib64/deadbeef/cdda.so
loading plugin /usr/lib64/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib64/deadbeef/flac.so
loading plugin /usr/lib64/deadbeef/hotkeys.so
loading plugin /usr/lib64/deadbeef/m3u.so
loading plugin /usr/lib64/deadbeef/mpgmad.so
loading plugin /usr/lib64/deadbeef/nullout.so
loading plugin /usr/lib64/deadbeef/oss.so
loading plugin /usr/lib64/deadbeef/sndfile.so
loading plugin /usr/lib64/deadbeef/supereq.so
loading plugin /usr/lib64/deadbeef/vfs_curl.so
loading plugin /usr/lib64/deadbeef/vorbis.so
selected output plugin: ALSA output plugin
INFO: loading playlist My Music
INFO: from file /home/foo/.config/deadbeef/playlists/0.dbpl
INFO: loading playlist My Music
INFO: from file /home/foo/.config/deadbeef/playlists/1.dbpl
gtkui plugin compiled for gtk version: 2.24.20
connecting button tray signals
gtkui: found cover-art loader plugin
quitting gtk
gtkui_stop completed
gui plugin has quit; waiting for mainloop thread to finish
plug_disconnect_all
plug_unload_all
stopping GTK2 user interface...
quitting gtk
gtkui_stop completed
stopping ALSA output plugin...
stopping Album Artwork...
stopping Hotkey manager...
stopping Null output plugin...
stopping OSS output plugin...
stopping WAV/PCM player...
stopping SuperEQ...
stopping cURL vfs...
stopping OggVorbis decoder...
stopped all plugins
all plugins had been unloaded
messagepump_free
plug_cleanup
hej-hej!
```

**Comment by Geyup** [comment] 2015-07-11 07:08
Alexey,

What distro are you running? Slackware 14.1 came out in 2013-11-07, so a lot of the system libs are older.

I also compiled deadbeef against GTK2, which did you use?

Slack uses these versions;
```
gtk+2-2.24.20
gtk+3-3.8.2
```

Like most bugs I run into, a lot of time, it's because of Slackwre's older versions, so maybe that's the problem here?

**Comment by Alexey-Yakovenko** [comment] 2015-07-11 08:58
So do you have a way to reproduce it? Can you find out what is happening?

I'm running Ubuntu 12.04, so it's older than your Slackware.

I don't think the problem is caused by your distro or GTK versions.

The easiest way to test is to use the prebuilt binaries, because you don't need to install them:

1. 0.6.2 with patches: http://sourceforge.net/projects/deadbeef/files/deadbeef-static_0.6.2-2_x86_64.tar.bz2/download
3. latest trunk: https://drone.io/github.com/Alexey-Yakovenko/deadbeef/files/portable_out/build/deadbeef-static_devel-1_x86_64.tar.bz2

just download and unpack in 2 folders, and run in the order you need.

then you can see whether the problem happens, and if it does - you can try backing up the configuration file, and compare it with the changed one.

Please let me know how it goes. And please stop posting the logs. They are useless for this bug, and look pretty much the same.

**Comment by Alexey-Yakovenko** [comment] 2015-07-11 10:45
Just to make sure that I understood your problem correctly: are you talking about design mode, right? Not about playlist column configuration?

You basically didn't give any proper description of what your problem is, so I have to guess.. And the idea just came, that maybe you're talking about playlist columns.

If so, then yeah -- migration from 0.6.2 to 0.7 is not done (yet).
But even so, the config is not lost. I you happen to come back to 0.6.2 -- the old config will be used.

**Comment by Geyup** [comment] 2015-07-12 00:49
Sorry about the logs, and before I try with the suggestions, let me post screen shots of what I'm seeing.

0.6.2;
http://i.imgur.com/rxXDKxt.jpg

GIT;
http://i.imgur.com/jKMeWCH.jpg

**Comment by Alexey-Yakovenko** [comment] 2015-07-12 07:10
This is what I thought :)

On your screenshots, the layout survives fine (additional panel on the right), but the playlist configuration resets. This is because title format has changed.

**Comment by Geyup** [comment] 2015-07-13 00:10
Sorry too that I didn't explain everything going on, because when I saw this message;

```(deadbeef:3281): WARNING **: Widget not found: Skip to_menu```

I just assumed it explained the problem.

Ok great, sounds good...

By the way, at first I didn't think I could put glib2 in /usr/local and have it work for an app I needed, but it is, so I still have the system default in /usr. So now begs the question, I wonder if I really should update to the latest git for any newer features. The changelog here on git says 11 months...

If there aren't to many things to explain, what are the differences between 0.6.2 and Git?

Keep up the great work.

Thanks

**Comment by Alexey-Yakovenko** [comment] 2015-07-13 07:15
The "Widget not found" is of course annoying, but it has nothing to do with (any) problems.

For glib2 problem, even tho this doesn't belong to this bug report.. If you want to stick with 0.6.2 until the next stable comes out -- you should just use one of the official builds, which contain the fix, or build from 0.6.2-fixes branch on git.

The difference between 0.6.2 and trunk is 11 months of work with over 700 commits.

Some of the important changes on trunk, which I could remember without digging into logs, are:

* better OSX/cocoaui support
* the new title formatting system (aiming to be compatible with fb2k)
* mpg123 support (in addition to libmad)
* a ton of bug fixes in pretty much every area

**Comment by Geyup** [comment] 2015-07-13 07:40
Hi,

Ok, so lots of fixes, hehe, sounds great!

Oh and again, I placed an updated glib2 in /usr/local, along with the system's default version in /usr...

Thanks Alexey, keep up the great work, I really love deadbeef, you've done an awesome job!

**Comment by Alexey-Yakovenko** [comment] 2015-07-13 08:38
Glad that you figured it out. Locking this issue because the conversation already is way out of topic.
