### ISSUE TITLE
Linux 0.7.2 - Design Mode - Album Art Display - Introduces Artifacts

### ISSUE THREAD

**Issue by Geyup** [Alexey-Yakovenko/deadbeef#1646] opened 2016-09-16 04:37 UTC
Hi Alexey,

My Specs:

Slackware 14.2 x86_64
deadbeef 0.7.2 (compiled from source)
gtk+2-2.24.31
gtk+3-3.18.9

I compiled deadbeef for GTK2 and GTK3, and I tested this on 3 different themes using both GTK2 & GTK3 for the gui and had the same results with the lines appearing.

I noticed when I used the Design Mode and added in a section for the album art display, and then adjusted the album art display window size, smaller or larger, it would introduce dark lines along the left and right edge of the images, and sometimes along the top and bottom.

I'm attaching a screen shot that you can see the album art image on the left side is just one color all the way around, and then the large album art display on the right side shows a thin dark line that has been added to the left and right edges of the image.

![deadbeef](https://cloud.githubusercontent.com/assets/13072581/18575401/f7d3c756-7bc6-11e6-9d11-5ee53fd13601.jpg)

**Comment by Alexey-Yakovenko** [comment] 2016-09-26 09:56
@Geyup 
I'm fairly sure, that Deadbeef is just using GtkImage widget, which is doing all of the image handling, including scaling. Can you provide the source image for closer inspection?

It might be that when it's reduced in size -- the vertical lines are not visible, but you can see them in higher resolution.

Also, does it happen with any images, or just this one?

**Comment by Lithopsian** [comment] 2016-09-26 15:41
Confirmed, that scaling is done by gdk_pixbuf_new_from_file_at_size().  The pixbuf may then be additionally scaled by cairo_scale() while the widget is being resized - you can spot the image going from blurred to sharp after a resize, especially when resizing from a very small to large widget.

The only time Deadbeef does its own scaling is for the notification bubble., and possibly third-party plugins that request scaled artwork.

I don't see anything here, but I may not be using the exact image you have and I'm almost certainly not using the same GTK version.

**Comment by Geyup** [comment] 2016-09-27 04:03
It happens with every image, and there are no borders around any of the images, that have this look with thin lines on the sides or tops...

Hmm

**Comment by Alexey-Yakovenko** [comment] 2016-09-27 16:41
@Geyup 

Please provide the test image, otherwise the bug stays closed, because there's no way to reproduce. Thanks for cooperation.

**Comment by Alexey-Yakovenko** [comment] 2016-09-27 16:42
Oh, I realized that you probably don't know how to get it...

It's somewhere in the ~/cache/deadbeef/.... by the name of artist/album.

**Comment by Geyup** [comment] 2016-09-28 23:57
I know where the images are.

And off topic here, I can also report this, unless it's a known bug already...

I've noticed when playing with deadbeef, not doing anything particular, the images for the covers in the cache will become corrupted, I had this happen a few times, and I ether delete and replace them or start deadbeef over to recreate them.

Now back On Topic :)

I've attached the image from the screen shot of the original.

![debut](https://cloud.githubusercontent.com/assets/13072581/18936488/3f3b2e4e-85d7-11e6-9e12-5da500dbb297.jpg)

**Comment by Alexey-Yakovenko** [comment] 2016-09-29 08:10
I tried with gtk3 and gtk2, could not see any vertical lines. Didn't try your image yet (have troubles with the network setup in my linux VM), but I will check it out later.

It still doesn't seem like this issue is caused by deadbeef.

> I've noticed when playing with deadbeef, not doing anything particular, the images for the covers in the cache will become corrupted, I had this happen a few times, and I ether delete and replace them or start deadbeef over to recreate them.

I've never seen this happening, and the old artwork plugin is now obsolete. The new artwork plugin is using less disk caching, and the cache structure / code is quite different. There's no sense to look into this, unless the new plugin will expose the same behaviour. However, it's only used on macOS and android right now (have not been ported to GTKUI yet).

**Comment by Geyup** [comment] 2016-09-30 04:08
I'm just an end-user, didn't consider this coming from somewhere else...

So a new artwork plugin with be coming out in a new release?

**Comment by Alexey-Yakovenko** [comment] 2016-09-30 07:51
Yes, it's already used in the Mac builds from master. Not fully complete yet though.

Reopening the issue, until it's reproduced (or not).

**Comment by Geyup** [comment] 2016-10-01 21:09
If this works from gdk-pixbuf and cairo as  Lithopsian mentioned, these are the versions Slackware 14.2 uses;

gdk-pixbuf2-2.32.3
cairo-1.14.6

**Comment by Alexey-Yakovenko** [comment] 2016-10-03 06:52
Can't reproduce with either gtk2 or gtk3, the picture looks fine, no dark lines around it.

Possibly newer GTK introduced new issues with image scaling, or your GTK theme is putting the border around any picture.

**Comment by Geyup** [comment] 2016-10-04 01:39
@Alexey-Yakovenko I don't mean you any disrespect, but just because you can't reproduce it, doesn't mean there isn't a bug here, or where it's even coming from, deadbeef or not...

Certainly one person saying they've found something, and another person saying they don't see anything, still for both you and me isn't ground enough to say yes or no honestly, so please keep this open until it can truly be proven.

thanks

**Comment by Geyup** [comment] 2016-10-04 01:45
I realized, best to not keep reedit the post over I was told in the past, that it keeps sending out to the developer.

The other thing to consider here is, if this was isolated to something smaller, then I can see your point to closing so easy.

But I've tried this on 5 different themes and also GTK2 & GTK3 and a half dozen pictures, and the results were still the same.

So this spans acorss any image I use, gtk2 or gtk2 and any theme I use, I'd say this is something fairly big in the bug department, to consider what is really going on here...

But again, let's just wait to see what happens with the new version of the artwork plugin, but let's please keep this open till then.

**Comment by Alexey-Yakovenko** [comment] 2016-10-04 06:42
I can keep it open if that's what you want.

> let's just wait to see what happens with the new version of the artwork plugin

There's no such bug in the artwork plugin, as there are no lines in the images produced by the artwork plugin in your screenshot. It's a bug (or rather a new feature) in GTK's image scaling.

The images in playlist -- that's artwork plugin loading and scaling them.

The image in the artwork widget -- that's GTK doing both loading and scaling.

Perhaps it would make sense for you to try another program which uses GTK, and trying to load any image in it. I'm pretty sure something like rythmbox would do.

**Comment by Alexey-Yakovenko** [comment] 2016-10-04 06:49
@Geyup 
Btw, I forgot to ask this.. Have you tried running precompiled deadbeef binaries, instead of the ones you compiled yourself? Does it change anything?

**Comment by Alexey-Yakovenko** [comment] 2016-10-04 07:08
Just tried the same on fedora24 (live image), still no problems, no black lines anywhere. The images look the same across playlist and the cover widget. I was using the prebuilt deadbeef binaries though.

**Comment by Alexey-Yakovenko** [comment] 2016-10-04 07:44
@Geyup I went as far as running slackware 14.2 x86_64 live image in virtualbox, and there are still no lines around the image.

![image](https://cloud.githubusercontent.com/assets/1895698/19065977/1d6c52e0-8a17-11e6-97a6-00e36268218f.png)

**Comment by Alexey-Yakovenko** [comment] 2016-10-04 07:47
@Geyup since this doesn't happen on the same OS as you have, can we consider this as your local problem, and close the issue? There doesn't seem to be a way to reproduce it.

**Comment by Alexey-Yakovenko** [comment] 2016-10-05 09:52
@Geyup a new idea... Could you provide a PNG screenshot of the problem?
It could be easier to see the origin of the lines. They could be scaling artefacts, gfx driver bug, UI toolkit borders, etc -- none of this could be seen after JPEG compression, so PNG might help.

**Comment by Alexey-Yakovenko** [comment] 2016-10-05 09:55
@Geyup And one more: could you try all the same stuff on the clean new user account, with default GTK settings, default GTK theme, preferably running the default system DE (I assume it's KDE in your case)?

**Comment by Geyup** [comment] 2016-10-05 23:26
@Alexey-Yakovenko 

Hi, I only run Openbox and it's a very clean minimal install I have. Everything is good and clean with the system.

I'd hate to need to backup my system and install Slack over with KDE and then compile and install deadbeef and deps, and test this for now...

I'm attaching a PNG screen shot, clean and untouched, as the cmd below;

bash -c "import /home/foo/ScreenShots/screenshot-$(date +%m-%d-%Y).png"

![deadbeef](https://cloud.githubusercontent.com/assets/13072581/19135287/098274ac-8b53-11e6-8b97-bb11a8533162.png)

**Comment by Geyup** [comment] 2016-10-06 00:18
@Alexey-Yakovenko off topic here, what's the best size to make the album cover images?

I'd like them all to be uniform in size...

Thanks Alexey

**Comment by Alexey-Yakovenko** [comment] 2016-10-06 05:43
> Hi, I only run Openbox and it's a very clean minimal install I have. Everything is good and clean with the system.
> I'd hate to need to backup my system and install Slack over with KDE and then compile and install deadbeef and deps, and test this for now...

I'm not asking you to do anything like this to your precious good and clean system.

Just adduser, run deadbeef, test the bug, delete the user.

It is nothing compared with what I had to do trying to help you - downloading and installing slackware from scratch.

Anyway, regarding the new png screenshot. That does not look like GTK bug/feature, and does not look like a scaling artifact. But it could be a gfx driver or cairo bug / feature.

So I suggest that you try playing with that. But first start with a clean user account.

At this point, there's nothing more that I could help you with, so I'm closing the issue.

Good bye!

> off topic here, what's the best size to make the album cover images?

I like them 4k by 4k :)

**Closed by Alexey-Yakovenko** 2016-10-06 05:43 UTC

**Comment by cboxdoerfer** [comment] 2016-10-06 06:02
@Geyup, you should definitely try the official static builds of deadbeef like Alexey already suggested. Preferably in a clean environment - new user account.

Btw. I also can't reproduce the bug with various distributions.
