### ISSUE TITLE
Drag and drop does not work on linux, Gnome on Wayland session

### ISSUE THREAD

**Issue by glaubersm** [Alexey-Yakovenko/deadbeef#1841] opened 2017-08-06 13:47 UTC
### Steps to reproduce the problem
Open deadbeef, open nautilus file manager, drag any audio file from nautilus to deadbeef window.

### What's going on? Describe the problem in as much detail as possible.
Drag and drop action is not completed.

### Information about the software:

Deadbeef version: 0.7.2
OS: Antergos (gnu/linux Arch-based system)
Gnome 3.24.2, Wayland session (DnD works on X11 session)

**Comment by Alexey-Yakovenko** [comment] 2017-08-06 14:08
Very likely a duplicate of #1822, can you verify it works either from master branch, or with the patch provided? https://github.com/Alexey-Yakovenko/deadbeef/commit/8201827d42e2ab37d097ba95cb1295d19f5acb78

**Comment by glaubersm** [comment] 2017-08-06 15:48
Sorry, I has no technical knowledge to apply the pach or compile master from source.

**Comment by Alexey-Yakovenko** [comment] 2017-08-06 16:38
You can download a pre-made build, see the readme (main page on github project)

**Comment by Alexey-Yakovenko** [comment] 2017-08-08 09:15
I installed Antegros, and tried to reproduce the bug in its GNOME session.
Drag-n-dropping files from file manager works fine.
I don't know how to see if it's running wayland or not.
Are there any extra steps to do?

**Comment by Alexey-Yakovenko** [comment] 2017-08-08 10:50
Ok, apparently it's not running wayland by default. Is there any documentation how to enable that?

**Comment by Alexey-Yakovenko** [comment] 2017-08-08 10:53
I installed wayland and weston, and weston has appeared as an option on the login screen. But when I try to log into the weston session -- it drops out back to the login screen.

Closing the bug as invalid, because impossible to reproduce based on the information provided.

**Closed by Alexey-Yakovenko** 2017-08-08 10:53 UTC

**Comment by glaubersm** [comment] 2017-08-08 14:25
I cant reproduce the bug anymore.
It was a temporary problem on my Wayland session.
Thanks for your attention.
