### ISSUE TITLE
DFF files don't play

### ISSUE THREAD

**Issue by laichiaheng** [Alexey-Yakovenko/deadbeef#1578] opened 2016-05-22 09:18 UTC
I installed DeaDBeeF from the deb package, will it work?
OS: Ubuntu 16.04

**Comment by KernelModule** [comment] 2016-05-23 10:44
It should be. https://github.com/Alexey-Yakovenko/deadbeef/commit/be5a65deb74067a0e2c0a845c565541397790b2d

**Comment by Alexey-Yakovenko** [comment] 2016-05-23 10:44
Depends which deb package, but yeah - it should work.

**Comment by laichiaheng** [comment] 2016-05-23 23:33
@KernelModule Where is that file on my PC?

**Comment by laichiaheng** [comment] 2016-05-24 02:30
I found that dsf and dff were selected by default, but it still doesn't work.

**Comment by Alexey-Yakovenko** [comment] 2016-05-24 06:38
@laichiaheng but can ffmpeg (ffplay) play the same files?

**Comment by laichiaheng** [comment] 2016-05-24 15:40
I can't find ffplay

**Comment by KernelModule** [comment] 2016-05-24 15:57
@laichiaheng Try avplay.

**Comment by laichiaheng** [comment] 2016-05-25 02:36
@KernelModule I can't find that, either.

**Comment by Alexey-Yakovenko** [comment] 2016-05-25 06:58
@laichiaheng please let us know when you find it, whether it can play dsf. It's not very interesting when you can't find something.

**Comment by Alexey-Yakovenko** [comment] 2016-05-25 07:04
@laichiaheng I'll try to explain a general idea to you..

Deadbeef can plays many file formats via FFMPEG. You can see which ones are enabled by default, in the FFMPEG plugin settings. You can add more if needed. FFMPEG supports many.

But sometimes ffmpeg can't play certain files, even if the format is supported.

In this case, deadbeef (obviously) wouldn't be able to play these files either.

So, the first thing you need to do - find out whether ffmpeg can play the file. The easiest is to run ffplay. I'm sure you know what google is, right? So please go and find the instruction how to get it on your computer. Then try playing the file.

If it plays -- then we can blame deadbeef for having a bug, and I will try to fix it. I would possibly ask you to send me the specific file.

If not -- then FFMPEG can't play the file, and you (quite obviously) need to be reporting the bug to FFMPEG bugtracker.

I hope that helps.

**Comment by KernelModule** [comment] 2016-05-25 10:10
@laichiaheng libav-tools is installed?

**Comment by laichiaheng** [comment] 2016-05-26 06:07
@KernelModule It will force me to install ffmpeg from apt.

I couldn't find that command because the ffmpeg which I installed was downloaded from the official website, after I installed it from apt, I found the ffplay.

Yes, it can be played by ffplay.

https://youtu.be/I_i2FH4khdk

> ffplay

 version 2.8.6-1ubuntu2 Copyright (c) 2003-2016 the FFmpeg developers
  built with gcc 5.3.1 (Ubuntu 5.3.1-11ubuntu1) 20160311
  configuration: --prefix=/usr --extra-version=1ubuntu2 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[iff @ 0x7f52ac009280] Estimating duration from bitrate, this may be inaccurate
Input #0, iff, from '01 - Jeff Chang - Ai Ru Chao Shui.dff':
  Metadata:
    artist          : Jeff Chang
    date            : 2013-13-02
    album           : The Essential Jeff Chang
    genre           : Rap
    encoder         : SACD Ripper release 0.21Copyright (c) 2010-2011 by respective authors.
                    : 
                    : Report bugs to mr_wicked@hotmail.com
                    : 
    track           : 1
    title           : Ai Ru Chao Shui
    general_remark  : Material ripped from SACD: The Essential Jeff Chang
    creating_machine: SACD Ripper release 0.21Copyright (c) 2010-2011 by respective authors.
                    : 
                    : Report bugs to mr_wicked@hotmail.com
                    : 
  Duration: 00:04:30.44, bitrate: 5644 kb/s
    Stream #0:0: Audio: dsd_msbf (DSD  / 0x20445344), 352800 Hz, stereo, fltp, 5644 kb/s
    Metadata:
      absolute_start_time: 00h:00m:02s:0
      comment_time    : 2014-05-17 11:23
SDL_OpenAudio (2 channels, 352800 Hz): Could not setup PulseAudio stream
SDL_OpenAudio (1 channels, 352800 Hz): Could not setup PulseAudio stream
  42.74 M-A: -0.000 fd=   0 aq=  418KB vq=    0KB sq=    0B f=0/0

**Comment by Alexey-Yakovenko** [comment] 2016-06-17 12:28
It seems like it's caused by missing IFF demuxer in deadbeef's version of ffmpeg.

**Comment by Alexey-Yakovenko** [comment] 2016-06-17 12:41
Yeah, adding IFF worked.
Fixed on OSX, will fix the Linux version later.

**Comment by JulianLai** [comment] 2016-06-18 14:36
Can we fix it for the version 0.7.2?

**Comment by Alexey-Yakovenko** [comment] 2016-06-18 15:58
Yes, I will make a new build as soon as I have some time.

**Comment by Alexey-Yakovenko** [comment] 2016-06-19 11:36
Fixed in the build 0.7.2-2

**Closed by Alexey-Yakovenko** 2016-06-19 11:36 UTC

**Comment by JulianLai** [comment] 2016-06-19 15:42
The speed of the playback is too slow, but OK with ffplay.

**Comment by Alexey-Yakovenko** [comment] 2016-06-19 16:31
@JulianLai
I verified that it plays the same in ffplay (Linux) and deadbeef (both OSX and Linux).

It's possible to get playback speed problems if the SRC plugin is not configured correctly.

If you can't figure out how to reset the SRC plugin settings to defaults -- delete this file: `~/.config/deadbeef/dspconfig`

**Comment by tianna1121** [comment] 2017-05-17 03:20
@Alexey-Yakovenko 
I have deleted the ~/.config/deadbeef/dspconfig. However the speed of the playback is still too slow. How to set the SRC plugin settings?

**Comment by Alexey-Yakovenko** [comment] 2017-05-17 05:46
> How to set the SRC plugin settings?

Edit -> Preferences -> DSP -> Make sure SRC plugin is in the list -> Select -> Click Configure.

**Comment by gehuangyi20** [comment] 2017-05-18 00:38
@Alexey-Yakovenko 

> Edit -> Preferences -> DSP -> Make sure SRC plugin is in the list -> Select -> Click Configure.

I cannot find the SRC plugin. my deadbeef is installed via following ppa https://launchpad.net/~hda-me/+archive/ubuntu/deadbeef-master

**Comment by Alexey-Yakovenko** [comment] 2017-05-18 06:09
@gehuangyi20 the plugin is called Resampler. If it's not in the list -- you can add it. If you can't add it -- the ppa is broken, and you should stop using it.

**Comment by tianna1121** [comment] 2017-05-22 12:59
@Alexey-Yakovenko If anyone tries to build deadbeef with Resampler support from source, please apt-get install libsamplerate-dev first.

**Comment by oleksiy-unity3d** [comment] 2017-05-22 12:59
@tianna1121 yes, that's exactly what you're supposed to do before building. It's in the README.

**Comment by Alexey-Yakovenko** [comment] 2017-05-22 13:00
@tianna1121 yes, that's exactly what you're supposed to do before building. It's in the README.
