### ISSUE TITLE
Scrobbling from radio sources breaks after a track or two

### ISSUE THREAD

**Issue by aamelin** [Alexey-Yakovenko/deadbeef#1235] opened 2015-07-24 12:02 UTC
Version 0.6.2
OS: Ubuntu 14.04 x86_64

1. Configure scrobbling
2. Start listening to a radio station which provides correct tags (eg: http://37.187.79.93:8178/stream).

Audiscrobbler plugin settings:
![selection_002](https://cloud.githubusercontent.com/assets/12884765/8875662/8bbe8580-3223-11e5-9175-c0b43d7d5fc8.png)

ER:
Each new track is scrobbled correct.
AR:
Only the first (and maybe the second) track is scrobbled. Also, pausing player breaks scrobbling.
If playback stopped and started again it scrobbles the current track but (most likely) won't scrobble following ones.

**Comment by Alexey-Yakovenko** [comment] 2015-07-24 12:14
Please provide a link to the radio which you use.

**Comment by aamelin** [comment] 2015-07-24 13:47
Updated the ticket.

**Comment by Alexey-Yakovenko** [comment] 2015-07-24 13:50
If you didn't change any other settings, radio should not have been scrobbled at all.

**Comment by Alexey-Yakovenko** [comment] 2016-10-05 13:40
Closing because the issue is too old, at lease needs to be re-tested with 0.7.2 or better the latest dev build

**Closed by Alexey-Yakovenko** 2016-10-05 13:40 UTC
