### ISSUE TITLE
Some albumart covers are not displayed/found anymore in 0.7.1

### ISSUE THREAD

**Issue by fladd** [Alexey-Yakovenko/deadbeef#1506] opened 2016-03-16 22:24 UTC
After upgrading to 0.7.1 some covers are not shown anymore, despite being present in the folder and having been shown in 0.7.0. I could not figure out what is special about the ones that are not shown anymore.

**Comment by Alexey-Yakovenko** [comment] 2016-03-16 22:34
The problem is that there were no changes in the artwork plugin in 0.7.1, except the version checking. Perhaps you forgot to enable fetching the covers from internet, or something like that?

**Comment by fladd** [comment] 2016-03-16 22:40
@Alexey-Yakovenko It is about local .jpg files. Nothing changed in my directory/file structure. I just updated via apt-get (on Mint, with the provided Ubuntu PPA), and a lot of covers are not shown anymore.

**Comment by fladd** [comment] 2016-03-16 22:49
Some more info: When switching "When no artwork is found" to "leave blank" and then back to "use Deadbeef default cover" and hitting apply, then some (all?) cover arts come back in the playlist.

**Comment by Alexey-Yakovenko** [comment] 2016-03-16 22:55
The only thing that I'm saying is that this can't technically be caused by upgrade from 0.7.0, because the artwork plugin hasn't changed.

It's probably caused by something else.

This is the diff -- you can see yourself that there are no changes except the versioning:

```
$ git diff 0.7.0 plugins/artwork/
diff --git a/plugins/artwork/artwork.c b/plugins/artwork/artwork.c
index 1abe05c..3aa2f0c 100644
--- a/plugins/artwork/artwork.c
+++ b/plugins/artwork/artwork.c
@@ -2171,7 +2171,7 @@ static DB_artwork_plugin_t plugin = {
     .plugin.plugin.api_vmajor = 1,
     .plugin.plugin.api_vminor = 0,
     .plugin.plugin.version_major = 1,
-    .plugin.plugin.version_minor = 2,
+    .plugin.plugin.version_minor = DDB_ARTWORK_VERSION,
     .plugin.plugin.type = DB_PLUGIN_MISC,
     .plugin.plugin.id = "artwork",
     .plugin.plugin.name = "Album Artwork",
diff --git a/plugins/artwork/artwork.h b/plugins/artwork/artwork.h
index 5a43baa..70e5c10 100644
--- a/plugins/artwork/artwork.h
+++ b/plugins/artwork/artwork.h
@@ -26,6 +26,8 @@
 
 #include "../../deadbeef.h"
 
+#define DDB_ARTWORK_VERSION 3
+
 typedef void (*artwork_callback) (const char *fname, const char *artist, const char *album, void *user_data);
```

**Comment by fladd** [comment] 2016-03-16 23:04
Yeah I believe you :-) Maybe something went wrong when packaging for this PPA or so. I also don't know. I just observed it and wanted to report it.

**Comment by Alexey-Yakovenko** [comment] 2016-03-16 23:32
Try deleting `~/.cache/deadbeef`, and see if it helps.

**Comment by Lithopsian** [comment] 2016-03-17 20:58
Changing the artwork preferences as described resets the artwork cache and so searches for all covers again.  That implies something weird in the cache, but I can't imagine what.  There is a mask that filters the filenames that will be considered as artwork, but it pretty much covers everything and is mostly just for which one to choose first.  Also no reason why the mask would change during the upgrade.

There is also a playlist context menu item to refresh cover art, which might help if artwork doesn't show up for some reason such as a temporary internet problem.

**Comment by fladd** [comment] 2016-03-17 22:35
Deleting the cache and readding all songs to the playlist will result in covers being shown.

**Comment by Alexey-Yakovenko** [comment] 2016-03-18 11:52
Well.. that means that the cache structure became incompatible between versions.

Since we can't guarantee that deadbeef would work correctly when the old cache is present, I guess we would need to change the cache path to something like `~/.cache/deadbeef072` in the next update, by default.

And add an option to configure it to point to arbitrary location, including the original ~/.cache/deadbeef, so that people can keep using their old scripts etc.

That is, if we lived in the perfect world.

Unfortunately, that's more trouble than it's worth.

Automatically deleting the cache is even worse, many people make it read-only for their cover-art conky scripts etc.

Therefore, if there are no other suggestions how to fix this.. Since there's an existing simple workaround, and no simple fix -- I'm closing this as wontfix.

**Closed by Alexey-Yakovenko** 2016-03-18 11:52 UTC
