### ISSUE TITLE
Embedded cuesheets in single flac files do not register, track titles are not extracted

### ISSUE THREAD

**Issue by roddersg** [Alexey-Yakovenko/deadbeef#1601] opened 2016-06-28 18:19 UTC
Embedded cuesheet in single flac does not register.  Although under track > metadata cuesheet is visible, track >properties > embedded cuesheet = 0 (not registered).  This results in track names not being displayed.
Have checked the flac file against foobar2000, and it shows that the cuesheet is present and embedded.
Have included screen shots for your reference.  I can supply the flac file if required.

![selection_007](https://cloud.githubusercontent.com/assets/6110578/16427576/857f4df6-3da0-11e6-841e-53b881dd3c31.png)
![properties - canon over a basso ostinato _008](https://cloud.githubusercontent.com/assets/6110578/16427426/e2026cbc-3d9f-11e6-9495-ef678a10c5c0.png)
![track properties_009](https://cloud.githubusercontent.com/assets/6110578/16427427/e207be24-3d9f-11e6-925b-0f3810285a55.png)
![track properties_010](https://cloud.githubusercontent.com/assets/6110578/16427428/e20fb57a-3d9f-11e6-8d18-f4e3995ae4dd.png)

**Comment by Alexey-Yakovenko** [comment] 2016-06-28 18:23
Pleast provide a test file to reproduce the problem, and specify which deadbeef version did you use.

**Comment by roddersg** [comment] 2016-06-28 18:40
Deadbeef version:  deadbeef 0.7.2 [static] [portable] (deadbeef-static_0.7.2-2_x86_64)

File: Various - Pachelbel's Greatest Hit~The Ultimate Canon.flac
Cusheet for checking: Various - Pachelbel's Greatest Hit~The Ultimate Canon.cue

You can get the files from : 
https://dl.dropboxusercontent.com/u/15635922/Various%20-%20Pachelbel's%20Greatest%20Hit~The%20Ultimate%20Canon.cue
https://dl.dropboxusercontent.com/u/15635922/Various%20-%20Pachelbel's%20Greatest%20Hit~The%20Ultimate%20Canon.flac

**Comment by Alexey-Yakovenko** [comment] 2016-06-28 18:45
Thanks, got the files.

**Comment by roddersg** [comment] 2016-06-28 18:49
BTW Deadbeef 0.6 handled the files ok.  I just saw the update tonight and decided to upgrade.  Then everything went haywire, as the formatter is now different.  I deleted the .config/Deadbeef folder to reset and everything is now amiss.
Deadbeef beats the lot in the class of players (I use squeezeserver/squeezeplayer for the streamed version, but my main system relies on Deadbeef)

**Comment by Alexey-Yakovenko** [comment] 2016-06-28 18:51
I believe you, but I can't fix the bug by reverting the player code back to 0.6 -- it has to be investigated again.

**Comment by Alexey-Yakovenko** [comment] 2016-06-28 18:57
Your test file works fine here, but I'm using the build from master (basically a future 0.8.0 version)

![image](https://cloud.githubusercontent.com/assets/1895698/16428567/c4864140-3d72-11e6-94c7-4a2626a18b48.png)

**Comment by Alexey-Yakovenko** [comment] 2016-08-01 11:16
Closing, because this seems to be fixed on master, and cannot be backported to 0.7 because of too many changes in the code.

**Closed by Alexey-Yakovenko** 2016-08-01 11:16 UTC
