### ISSUE TITLE
Crash when adding songs with Unicode chars

### ISSUE THREAD

**Issue by thefallenidealist** [Alexey-Yakovenko/deadbeef#1774] opened 2017-05-13 22:52 UTC
### Problem
DeadBeeF will crash if I try to add folder or file with Unicode chars in ID3 tags

### Versions
OS: FreeBSD 11.0-RELEASE-p10 amd64
DeaDBeeF installed with FreeBSD pkg
% deadbeef --version 
starting deadbeef 0.7.2
DeaDBeeF 0.7.2 Copyright © 2009-2016 Alexey Yakovenko

file:
% id3 02\ -\ Old\ Man.mp3
File: 02 - Old Man.mp3
Metadata: ID3v2.3
Title: Old Man (Väinämöinen)
Artist: Ensiferum
Album: Demo I (Demo)
Track: 2/3
Year: 1997
Genre: Viking / Folk Metal

### GDB trace:
```gdb
Program received signal SIGBUS, Bus error.
[Switching to Thread 80b8a0700 (LWP 100726/deadbeef)]
_citrus_iconv_open (rcv=0x7fffde7ee518, src=0x206e614d20646c4f <Error reading address 0x206e614d20646c4f: Bad address>, dst=0x42fc10 "utf-8")
    at /usr/src/lib/libc/iconv/citrus_iconv.c:289
289             if ((strcmp(src, "") == 0) || (strcmp(src, "char") == 0))
Current language:  auto; currently minimal
(gdb) bt
#0  _citrus_iconv_open (rcv=0x7fffde7ee518, src=0x206e614d20646c4f <Error reading address 0x206e614d20646c4f: Bad address>, 
    dst=0x42fc10 "utf-8") at /usr/src/lib/libc/iconv/citrus_iconv.c:289
#1  0x0000000801416efc in __bsd___iconv_open (out=0x42fc10 "utf-8", 
    in=0x206e614d20646c4f <Error reading address 0x206e614d20646c4f: Bad address>, handle=0x817a0e1b0) at /usr/src/lib/libc/iconv/bsd_iconv.c:77
#2  0x0000000000419618 in ?? ()
#3  0x0000000000419d02 in ?? ()
#4  0x0000000813c2819b in mp3_load () from /usr/local/lib/deadbeef/mp3.so
#5  0x000000000040b045 in ?? ()
#6  0x000000000040b54c in ?? ()
#7  0x000000000040b514 in ?? ()
#8  0x000000000040fe9f in ?? ()
#9  0x0000000802054066 in gtkpl_add_dirs () from /usr/local/lib/deadbeef/ddb_gui_GTK2.so
#10 0x00000008047e131d in g_slist_foreach () from /usr/local/lib/libglib-2.0.so.0
#11 0x0000000802053fbf in gtkpl_add_dirs () from /usr/local/lib/deadbeef/ddb_gui_GTK2.so
#12 0x00000008020541eb in gtkui_add_dirs () from /usr/local/lib/deadbeef/ddb_gui_GTK2.so
#13 0x0000000800d8ab55 in pthread_create () from /lib/libthr.so.3
#14 0x00007fffde5f2000 in ?? ()
Error accessing memory address 0x7fffde7f2000: Bad address.
(gdb) l
77                      ret = _citrus_iconv_open(&handle, in, out);
78              }
79
80              if (ret) {
81                      errno = ret == ENOENT ? EINVAL : ret;
82                      return ((iconv_t)-1);
83              }
84
85              handle->cv_shared->ci_discard_ilseq = strcasestr(out, "//IGNORE");
86              handle->cv_shared->ci_ilseq_invalid = false;
```

**Comment by Alexey-Yakovenko** [comment] 2017-05-14 08:09
Thanks for your bug report, and the backtrace, but this is a duplicate of #1693

**Closed by Alexey-Yakovenko** 2017-05-14 08:09 UTC
