### ISSUE TITLE
Parallel encoding

### ISSUE THREAD

**Issue by BratSinot** [Alexey-Yakovenko/deadbeef#1728] opened 2017-03-16 15:35 UTC
Hello there!

Any way to implement parallel encoding as in foobar2000?

**Comment by Alexey-Yakovenko** [comment] 2017-03-16 15:37
There is a way, and I hope it will be implemented at some point. It was even implemented some time ago, and pull request was submitted, but the code quality was not good enough to be accepted, and the developer decided to stop working on it.

**Comment by Alexey-Yakovenko** [comment] 2017-03-16 15:37
Also, this issue is a duplicate of #1116

**Closed by Alexey-Yakovenko** 2017-03-16 15:37 UTC
