### ISSUE TITLE
[tf] $strcmp() fails for condition "%channels%" == "mono"

### ISSUE THREAD

**Issue by andreas--e** [Alexey-Yakovenko/deadbeef#1203] opened 2015-03-29 20:15 UTC
Even at this early stage, fb2k-style title formatting is working much better than I thought. Excellent work.

`$if($strcmp("%channels%","stereo"),st,mo)`

works indeed with my playlist. Tracks rechecked with avprobe to check for some false positives - none there.

Reversing the condition...
`$if($strcmp("%channels%","mono"),mo,st)`

...will also cause the parser to jump to the second ('st') condition with my mono tracks.
I suppose comparison fails because there is something before and/or after the "mono" string...
(Alas, couldn't work around it by adding $trim() as it does not appear to be implemented in current master.)

**Comment by cboxdoerfer** [comment] 2015-03-31 19:55
Both expressions work fine here. Does this happen with every mono track? and are you sure there's only one channel listed in track properties?

**Comment by andreas--e** [comment] 2015-03-31 22:05
Checked track properties, only 1 channel, all of them. And yes, it appears to happen with every mono track.
Second expression (the one following up the "Reversing..." line) *never* works with *any* mono track as it shows. 100% proved by using a huge playlist with some mono tracks scattered amongst and sorting by the test column. 'st' everywhere.

**Comment by Alexey-Yakovenko** [comment] 2015-04-23 09:30
Closing because the description is confusing / inaccurate, and I can't reproduce any of the mentioned problems.

**Closed by Alexey-Yakovenko** 2015-04-23 09:30 UTC

**Comment by cboxdoerfer** [comment] 2015-04-23 09:43
Can't reproduce that either with the new description.

**Comment by Alexey-Yakovenko** [comment] 2015-04-23 09:45
Managed to reproduce in the end. Fixed.

**Comment by andreas--e** [comment] 2015-04-23 13:32
thanks!
