### ISSUE TITLE
stream radio does not work

### ISSUE THREAD

**Issue by dronord** [Alexey-Yakovenko/deadbeef#1834] opened 2017-07-15 04:56 UTC
### Steps to reproduce the problem
Press Play
### What's going on? Describe the problem in as much detail as possible.
Silence
### Information about the software:
Deadbeef version: 0.6.2, 0.7.2
OS: Fedora 25 x64

http://radionina.ru/stream320 - work
http://radionina.ru/streamflac - does not work

**Comment by Alexey-Yakovenko** [comment] 2017-07-18 21:07
duplicate of #1122

**Closed by Alexey-Yakovenko** 2017-07-18 21:07 UTC
