### ISSUE TITLE
hotkeys: allow mapping to mouse buttons

### ISSUE THREAD

**Issue by Soukyuu** [Alexey-Yakovenko/deadbeef#1450] opened 2016-01-16 22:46 UTC
I'd like to be able to map actions to mouse keys, for example having mouse next/back buttons mapped to next/previous track and the middle button to "add to playback queue". Would that be possible to do?

**Comment by Alexey-Yakovenko** [comment] 2016-01-17 17:07
duplicate of #525

**Closed by Alexey-Yakovenko** 2016-01-17 17:07 UTC
