### ISSUE TITLE
[Android] long id3-tags causes crash app

### ISSUE THREAD

**Issue by Chereq** [Alexey-Yakovenko/deadbeef#1259] opened 2015-09-03 19:19 UTC
If the tag name and value longer than 2046 chars player crashes when file added to playlist.

**Comment by Alexey-Yakovenko** [comment] 2016-10-01 11:27
Can't reproduce on latest trunk, probably already fixed. This problem is not going to be fixed in deadbeef 1 on android, but the version 2 will have the fix.

**Closed by Alexey-Yakovenko** 2016-10-01 11:27 UTC
Labels: bug
