### ISSUE TITLE
Refresh cover art -> Segmentation Fault

### ISSUE THREAD

**Issue by CaPusto** [Alexey-Yakovenko/deadbeef#1461] opened 2016-02-01 13:43 UTC
Hello!
After choice "Refresh cover art" I got "Segmentation Fault".
My system is CentOS 7 64-bit.

>uname -a
Linux ed.localdomain 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Deafbeef 0.7.0 static portable build x86_64 

```
 Segmentation Fault
backtrace() returned 29 addresses
./Progs/deadbeef-0.7.0/deadbeef() [0x403ab3]
/lib64/libc.so.6(+0x35670) [0x7f78fa702670]
/home/ed/Progs/deadbeef-0.7.0/plugins/artwork.so(remove_cache_item+0xbb) [0x7f78eabc29fb]
/home/ed/Progs/deadbeef-0.7.0/plugins/artwork.so(+0x1727a) [0x7f78eabc027a]
/lib64/libgobject-2.0.so.0(g_closure_invoke+0x138) [0x7f78f2bd3e38]
/lib64/libgobject-2.0.so.0(+0x2175d) [0x7f78f2be575d]
/lib64/libgobject-2.0.so.0(g_signal_emit_valist+0xe11) [0x7f78f2bed4c1]
/lib64/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f78f2bed77f]
/lib64/libgtk-x11-2.0.so.0(gtk_widget_activate+0x7c) [0x7f78f3ae40dc]
/lib64/libgtk-x11-2.0.so.0(gtk_menu_shell_activate_item+0xfd) [0x7f78f39ca67d]
/lib64/libgtk-x11-2.0.so.0(+0x15da51) [0x7f78f39caa51]
/lib64/libgtk-x11-2.0.so.0(+0x14832c) [0x7f78f39b532c]
/lib64/libgobject-2.0.so.0(g_closure_invoke+0x138) [0x7f78f2bd3e38]
/lib64/libgobject-2.0.so.0(+0x2151b) [0x7f78f2be551b]
/lib64/libgobject-2.0.so.0(g_signal_emit_valist+0xafc) [0x7f78f2bed1ac]
/lib64/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f78f2bed77f]
/lib64/libgtk-x11-2.0.so.0(+0x2784d4) [0x7f78f3ae54d4]
/lib64/libgtk-x11-2.0.so.0(gtk_propagate_event+0xc4) [0x7f78f39b3554]
/lib64/libgtk-x11-2.0.so.0(gtk_main_do_event+0x31b) [0x7f78f39b394b]
/lib64/libgdk-x11-2.0.so.0(+0x6091c) [0x7f78f309a91c]
/lib64/libglib-2.0.so.0(g_main_context_dispatch+0x15a) [0x7f78f26d47aa]
/lib64/libglib-2.0.so.0(+0x49af8) [0x7f78f26d4af8]
/lib64/libglib-2.0.so.0(g_main_loop_run+0x6a) [0x7f78f26d4dca]
/lib64/libgtk-x11-2.0.so.0(gtk_main+0xb7) [0x7f78f39b2997]
/home/ed/Progs/deadbeef-0.7.0/plugins/ddb_gui_GTK2.so(gtkui_thread+0x722) [0x7f78f3f24af2]
/home/ed/Progs/deadbeef-0.7.0/plugins/ddb_gui_GTK2.so(+0x33d6c) [0x7f78f3f24d6c]
./Progs/deadbeef-0.7.0/deadbeef() [0x403776]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f78fa6eeb15]
./Progs/deadbeef-0.7.0/deadbeef() [0x4039b8]

```

**Comment by Alexey-Yakovenko** [comment] 2016-02-01 13:52
Thanks for reporting. Seems like a bug in the refresh implementation.
For now, the best workaround for this problem is to avoid clicking the refresh button/menu, and clean the cache manually (delete ~/.cache/deadbeef)

**Comment by massdest** [comment] 2016-02-01 19:29
same problem on xubuntu 15.04

```
gtkui: found cover-art loader plugin

** (deadbeef:19702): WARNING **: Widget not found: Skip to_menu

(deadbeef:19702): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_file: assertion 'filename != NULL' failed
Segmentation Fault
backtrace() returned 30 addresses
deadbeef() [0x403c01]
/lib/x86_64-linux-gnu/libc.so.6(+0x352f0) [0x7fb71eaee2f0]
/usr/lib/deadbeef/ddb_gui_GTK2.so(cover_get_default_pixbuf+0x10a) [0x7fb71e471efa]
/usr/lib/deadbeef/ddb_gui_GTK2.so(draw_column_data+0xabf) [0x7fb71e473eef]
/usr/lib/deadbeef/ddb_gui_GTK2.so(ddb_listview_list_render_album_art+0xb2) [0x7fb71e462962]
/usr/lib/deadbeef/ddb_gui_GTK2.so(ddb_listview_list_render+0x5f6) [0x7fb71e463796]
/usr/lib/deadbeef/ddb_gui_GTK2.so(ddb_listview_list_expose_event+0x82) [0x7fb71e463bf2]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0x132d1f) [0x7fb71df02d1f]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x145) [0x7fb71cd202d5]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2203c) [0x7fb71cd3203c]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xae5) [0x7fb71cd3a1a5]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7fb71cd3a8ff]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0x24a61c) [0x7fb71e01a61c]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_main_do_event+0x552) [0x7fb71df01aa2]
/usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0(+0x41bdf) [0x7fb71db5bbdf]
/usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0(+0x41b85) [0x7fb71db5bb85]
/usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0(+0x41b85) [0x7fb71db5bb85]
/usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0(+0x3e6b8) [0x7fb71db586b8]
/usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0(gdk_window_process_all_updates+0x118) [0x7fb71db58fe8]
/usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0(+0x3f049) [0x7fb71db59049]
/usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0(+0x1ddd7) [0x7fb71db37dd7]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x15d) [0x7fb71c848b4d]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x49f20) [0x7fb71c848f20]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0xc2) [0x7fb71c849242]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_main+0xb7) [0x7fb71df00857]
/usr/lib/deadbeef/ddb_gui_GTK2.so(gtkui_thread+0x752) [0x7fb71e448ad2]
/usr/lib/deadbeef/ddb_gui_GTK2.so(+0x2dd09) [0x7fb71e448d09]
deadbeef() [0x4038b0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fb71ead9a40]
deadbeef() [0x403ae9]
```

**Comment by CaPusto** [comment] 2016-02-01 20:17
> For now, the best workaround for this problem is to avoid clicking the refresh button/menu, and clean the cache manually (delete ~/.cache/deadbeef)

Thanks, Alexey.
But I think the problem here is somewhat different.
Directory "~ / .cache / deadbeef" is absent in general.
I just created this directory. And this error no longer occurs.

**Comment by Alexey-Yakovenko** [comment] 2016-02-01 20:44
don't worry mate, we'll figure out what to fix. I was just trying to help while you're waiting for the fix.

**Comment by Lithopsian** [comment] 2016-02-01 23:21
Didn't you fix this already?  There used to be a crash when ~ / .cache / deadbeef didn't exist, fixed by commit [11d1148](https://github.com/Alexey-Yakovenko/deadbeef/commit/11d1148e949b0b71a4ca09f50aabf9e2ccbe2c92#diff-2205ec6f149409166a670e87ffde3a94).

I'm not sure how come you don't ever have ~ / .cache / deadbeef.  To test, I removed all permissions from this and 0.7.0 static build crashed.  My trunk build didn't crash.

**Comment by Lithopsian** [comment] 2016-02-01 23:40
The second issue is different.  Is this happening when you click refresh artwork?  The assert says the filename is null, yet the previous line of code explicitly checks that it isn't null.  Could one thread be resetting it while another is trying to use it?  I can't reproduce this here.

**Comment by massdest** [comment] 2016-02-02 20:03
Hello, figure it out, my local problems, previously had deadbeef 0.6.2.2-1~vivid~ppa1 from ppa, and now build from source in /usr, after cleaning deadbeef 0.6.2.2 and reinstall 0.7 from source - all fine.

**Comment by Lithopsian** [comment] 2016-02-02 21:42
> Hello, figure it out, my local problems, previously had deadbeef 0.6.2.2-1~vivid~ppa1 from ppa, and now build from source in /usr, after cleaning deadbeef 0.6.2.2 and reinstall 0.7 from source - all fine. 

That's good.  I think this is all fixed.

**Comment by Alexey-Yakovenko** [comment] 2016-02-03 09:22
I can't reproduce this either. I think this is caused by mixing artwork plugin from 0.6.2 with GTKUI plugin from 0.7.0.

I will add a check for this situation

**Closed** 2016-02-03 09:25 UTC
Labels: bug
