### ISSUE TITLE
New playlist from selection

### ISSUE THREAD

**Issue by dsx** [Alexey-Yakovenko/deadbeef#1468] opened 2016-02-02 16:20 UTC
This is a feature request.

It would be quite convenient to have an option to create new playlist from selected tracks.

**Comment by dronord** [comment] 2016-02-08 09:46
**How-to**
Ctrl+N
Select tracks
Drag and Drop tracks to previous created list

M?

**Comment by Alexey-Yakovenko** [comment] 2016-02-08 10:50
yeah, it's possible to do using d-n-d, and this issue is actually kinda a duplicate of #655

**Closed by Alexey-Yakovenko** 2016-02-08 10:50 UTC
Labels: enhancement

**Comment by dsx** [comment] 2016-02-08 18:28
Requires 3 (three!) actions instead of one. But yeah whatever.
