### ISSUE TITLE
Sorting doesn't understand numbers

### ISSUE THREAD

**Issue by markonius** [Alexey-Yakovenko/deadbeef#1579] opened 2016-05-26 14:53 UTC
When sorting by a custom column, the order of numbers gets mixed up.
(Example: 1, 10, 11, 12,..., 2, 20, 21, 22, 3...
Here's a screenshot: [http://i.imgur.com/rSgItUr.png](http://i.imgur.com/rSgItUr.png)

**Comment by Alexey-Yakovenko** [comment] 2016-07-05 07:25
Closing as duplicate of #1607

**Closed by Alexey-Yakovenko** 2016-07-05 07:25 UTC
Labels: enhancement
