### ISSUE TITLE
Missing tray icon

### ISSUE THREAD

**Issue by kehugter** [Alexey-Yakovenko/deadbeef#1208] opened 2015-04-23 20:41 UTC
**What steps will reproduce the problem?**

Start deadbeef, tray icon is missing.

**What is the expected output? What do you see instead?**

Deadbeef icon should be in the tray (configured to be shown permanently). Instead, an empty space where the icon should be is created, no tooltip text when hovering.

**What version of the product are you using? On what operating system and CPU architecture?**

deadbeef 0.6.2
Linux Mint 17.1 Cinnamon 64bit

**How did you install the product?**

apt repositry

**Please provide any additional information below.**

Preferences -> GUI/Misc -> check and uncheck again "Hide system tray icon" make the icon appear, until deadbeef is restarted.

This is not the same as #1028, just in case.

**Comment by Alexey-Yakovenko** [comment] 2015-04-24 07:05
Why is this bug reported to deadbeef instead of cinnamon?

**Comment by Alexey-Yakovenko** [comment] 2015-04-24 09:37
I booted into mint17.1 cinnamon 64 bit live CD, downloaded the deadbeef 0.6.2-2, and launched it.

The tray icon doesn't appear (as expected, because cinnamon doesn't have the X system tray enabled by default, and I couldn't find any way to enable it)
The empty space described in the bug doesn't appear either.
I tried clicking the "Hide system tray icon" multiple times in ddb preferences.

Closing because can't reproduce.

Relevant bugs on linux mint bug tracker:

https://bugs.launchpad.net/linuxmint/+bug/1333287
https://bugs.launchpad.net/linuxmint/+bug/1324503

**Closed by Alexey-Yakovenko** 2015-04-24 09:37 UTC

**Comment by kehugter** [comment] 2015-04-24 11:27
Tried with the (I assume) latest deadbeef downloaded from [here](https://drone.io/github.com/Alexey-Yakovenko/deadbeef/files), still didn't work in my case. But it looks like it's a random Cinnamon bug as you suggest. Here's a issue describing the same behaviour

https://github.com/linuxmint/Cinnamon/issues/2566

**Comment by Alexey-Yakovenko** [comment] 2015-04-24 11:45
> still didn't work in my case

That's what I wrote above. It doesn't work for me either.
It is not supposed to work.
I don't understand why you filed a deadbeef bug about something that doesn't work because _it's not supposed_ to work by design" in Cinnamon.

**Comment by kehugter** [comment] 2015-04-24 19:12
> I don't understand why you filed a deadbeef bug about something that doesn't work because it's not supposed to work by design in Cinnamon.

Because I didn't know that beforehand. Geez...

**Comment by Alexey-Yakovenko** [comment] 2015-04-24 20:25
Anyway, if you need system tray -- you should be more picky about what desktop environment you use in linux. KDE, XFCE and most standalone panels for light weight WMs have system tray working. Unity, GNOME3 and the forks -- don't.
(Sorry, I didn't mean to be offensive, but now after reading my comments it looks like I was)

**Comment by shadowlmd** [comment] 2015-09-01 20:21
Sorry for bringing it up, I didn't get why it shouldn't work on Unity/GNOME3? A lot of software displays tray icons on Ubuntu, only deadbeef doesn't for some reason.

**Comment by Alexey-Yakovenko** [comment] 2015-09-01 21:04
It's not "only deadbeef". XEmbed system tray is considered deprecated in Unity, GNOME, KDE and Cinnamon. This is what deadbeef is using - this is why the icon doesn't (and won't) work. The reasons why system tray _should not_ be used in _some_ of the mentioned desktop environments are different. E.g. it's _supposed_ to be present in KDE, but not supposed to be present in Unity. Because of design guidelines. Because it would duplicate the Unity's dock functionality. The new dbus status notifier work is ongoing on the statusnotifier branch. Hope that helps.

**Comment by boussou** [comment] 2020-01-05 17:08
Still not working on Cinnamon for me. Even with the XApp status applet.
No workaround?

**Comment by simonwiles** [comment] 2020-05-10 20:05
@boussou make sure you have "Hide system tray icons for compatible players" disabled in the sound applet config:

![image](https://user-images.githubusercontent.com/96218/81509352-e0223080-92be-11ea-8528-5a236a673bd9.png)
