### ISSUE TITLE
No covers for ogg files

### ISSUE THREAD

**Issue by RazrFalcon** [Alexey-Yakovenko/deadbeef#1709] opened 2017-02-06 22:21 UTC
Covers for OGG files with VORBIS codec doesn't show up. MP3 and FLAC works fine.

Gentoo Linux
Version: 0.7.2

**Comment by Alexey-Yakovenko** [comment] 2017-02-08 15:51
duplicate of #985

**Closed by Alexey-Yakovenko** 2017-02-08 15:51 UTC
Labels: duplicate
