### ISSUE TITLE
gtk3 ui broken colors

### ISSUE THREAD

**Issue by Ravenow** [Alexey-Yakovenko/deadbeef#1615] opened 2016-07-30 10:07 UTC
Hi, i have gnome-3.20 with adwaita theme(all defaults here for fedora 24). But for gtk3 ui some controls(track length, volume) looks invisible :) c pic. AFAIR gtk2 ui has no such problems.

Thanks.

![2016-07-30 13-03-36](https://cloud.githubusercontent.com/assets/20242363/17269625/2d15d15c-5656-11e6-9ef0-4325d4a0b2ea.png)

**Comment by Alexey-Yakovenko** [comment] 2016-07-30 10:51
duplicate of #1547

**Closed by Alexey-Yakovenko** 2016-07-30 10:51 UTC
