### ISSUE TITLE
Will it support for replaygain caculation?

### ISSUE THREAD

**Issue by laichiaheng** [Alexey-Yakovenko/deadbeef#1351] opened 2015-11-26 04:41 UTC
I usually have to do it with soundkonverter, DeaDBeeF should be able to do it.

**Comment by Alexey-Yakovenko** [comment] 2015-11-26 07:50
http://github.com/Soukyuu/ddb_misc_replaygain_scan

**Comment by Alexey-Yakovenko** [comment] 2015-11-26 07:50
Closing as a duplicate of #493

**Closed by Alexey-Yakovenko** 2015-11-26 07:50 UTC
