### ISSUE TITLE
Regression of sound quality.

### ISSUE THREAD

**Issue by krassswr** [Alexey-Yakovenko/deadbeef#1541] opened 2016-04-10 18:39 UTC
I was using 0.6.2 and sound quality was good. Now I install new deb packet and while play I hear strange noises like when your amplifier or speakers are damaged while play low freq. sounds. I installed back 0.6.2 and there is no problem with sound. In new version I see option for cp1251 was replaced with cp1252... can you please leave both options? Anyway I have mp3 files with cyrillic names in id3 info and in listing they look like this:  "Äèêà Åíåðã³ÿ (synthetic mix)"

**Comment by Alexey-Yakovenko** [comment] 2016-04-10 18:50
Hello.

I don't think that deadbeef has any regressions in sound quality, but if you provide a way to reproduce the bug on my computer, I would be happy to fix it.

There was no change from cp1251 to cp1252 either. I think you're wrong about it.

Regarding the file which shows up with wrong encoding: there can be a number of reasons for that, but most obvious thing is that detection simply cannot work in 100% cases, and when this happens -- the easiest solution is to fix the text manually, and write the tag in Unicode.

Hope that helps.

I'm closing this issue, because it doesn't have any information which could be used as a valid bug report, or a feature request..

**Closed by Alexey-Yakovenko** 2016-04-10 18:50 UTC
