### ISSUE TITLE
Deadbeef player becoming unusable during adding music

### ISSUE THREAD

**Issue by deriv** [Alexey-Yakovenko/deadbeef#1626] opened 2016-08-15 09:32 UTC
When music is added to the Deadbeef (0.72), player can't be used nor interacted in any way until all the files have been added. This is an issue especially when adding big local libraries. Suggestion is to change music adding to an (optional) background process, which would not halt the player itself.

Also I would like to suggest adding an option to set watch folder(s) for music in Preferences.

**Comment by Alexey-Yakovenko** [comment] 2016-08-15 09:33
Duplicate of #690

**Closed by Alexey-Yakovenko** 2016-08-15 09:33 UTC
