### ISSUE TITLE
gtkui: change click behavior in listview

### ISSUE THREAD

**Issue by cboxdoerfer** [Alexey-Yakovenko/deadbeef#1293] opened 2015-10-18 10:58 UTC
While working on a fix for this bug (#1288) I found some odd behaviors with click handling in the listview which I'd like to fix/update.

Here's how we handle mouse clicks currently (italic being the stuff I find really odd/buggy):

area | single click | double click | SHIFT + single click | CTRL + single click
----- | -------------- | --------------- | ------------------------- | ------------------------
**track** | only select track and set cursor on track | play track | select all tracks from cursor to clicked track and set cursor on clicked track | toggle selection of the track and set cursor on track
**group title** | select the group and set cursor to first group item | _play the first track in the group and only select the first track in it_ | _select all tracks from cursor to first item in the group and set cursor to it_ | _toggle selection of the first track in the group_
**album art** | same as group title | ... | ... | ...
**area below album art** | same as group title | ... | ... | ...
**empty space below tracks** | deselect everything | single click action and nothing | _select all tracks from cursor to the last item of the previous group_ | nothing

foobar2000 handles it like that (* same as DeaDBeeF):

area | single click | double click | SHIFT + single click | CTRL + single click
----- | -------------- | --------------- | ------------------------- | ------------------------
**track** | * | * | select all tracks from first cursor pos(**) to clicked track, then set cursor to clicked track | *
**group title** | * | play the first track in the group and keep the whole group selected | select all tracks in the group and set cursor on first track in the group | toggle selection of all tracks in the group (if one or more tracks are selected deselect everything)
**album art** | same as group title | ... | ... | ...
**area below album art** | same as empty space below tracks | ... | ... | ...
**empty space below tracks** | * | * | nothing | *

(**) the first cursor position is remembered during multiple SHIFT + single click operations and is only updated with other operations like single click or CTRL + single click.

I think especially the handling of SHIFT/CTRL + single click on group title or album art should be updated, cause currently it really doesn't make any sense. So I'd really like to get an opinion about how you think it's supposed to work. Personally I like how foobar2000 does it.

**Comment by Alexey-Yakovenko** [comment] 2015-10-18 11:09
It sounds reasonable. Fix whatever you feel needs fixing.

I just tried the shift+click on empty space in fb2k, and it feels good, but deadbeef impl has never made me uncomfy either.

the shift+click selection, this is implemented differently in different programs and OSs. we need to be careful with it, and test what other GTK programs do, rather than comparing with fb2k on windows.

**Comment by cboxdoerfer** [comment] 2015-10-18 11:37
Just tried some GTK+ and Qt applications and SHIFT+click on single items works just like in foobar2000 (or WIN32 listviews etc.). Personally I find both approaches logical, but I guess it would make sense for ddblistview to work just like GTKs' listview, for consistency. On the other hand a lot of deadbeef users might already be used to the current behavior.

The problem with SHIFT+click on empty space currently is the following:
**current selection:**
![](https://i.imgur.com/7US5uxr.png)


**shift+click on empty space under "Behind Space - Live":**
![](https://i.imgur.com/jFJqc0X.png)

This is really odd and doesn't make any sense. What I expect is either select every tracks between cursor and mouse click or (like foobar2000 or gtk listview do, do nothing).

**Comment by Alexey-Yakovenko** [comment] 2015-10-19 14:20
@cboxdoerfer Perhaps you could look into fixing the bug #1138 as well while looking into it..

**Comment by Lithopsian** [comment] 2015-10-20 22:59
Slightly off-topic, but I've been looking at reducing the number of redraw calls, especially for cover art.  I've added a clip rectangle for the GTK3 draw event, and don't draw at startup until the scroll positions have been set, but I noticed a lot of full list refreshes being done when the selection changed.  The culprit seems to be ddb_listview_select_single().  Selecting multiple items or deselecting just draws the current row or group, but ddb_listview_select_single() always refreshes the whole playlist, even if the selection didn't change (eg. a mouse click on the selected item or a page up while at the top of the list).  Not the end of the world, but maybe worth a look.

**Comment by Alexey-Yakovenko** [comment] 2015-10-21 06:52
@Lithopsian  it's because single selection can also deselect items, which also need redrawing, and it's very hard to detect and configure this individual track redrawing.

**Comment by cboxdoerfer** [comment] 2015-10-21 16:46
Yes, I'll have a look at both.

**Comment by Lithopsian** [comment] 2015-10-26 14:06
You might find it difficult to distinguish "area below album art" from the album art itself, and in some cases it is impossible.

Album art is drawn in a space which is the width of its column, less some padding, and a height determined by the larger of the height of the playlist rows and a minimum height.  The minimum height is effectively the same as the album art column width, give or take some padding.  The minheight calculation is currently hardcoded in the ddb_listview_build_groups, but my ongoing pull request provides a minheight callback on each column so that the padding is accounted for properly.

So for square images you can have a good idea where the album art was drawn, although the information isn't stored explicitly anywhere.  For non-square images, you have no idea where the album art is and where is blank space that the image didn't cover.  For narrow images, any extra blank area will be to either side of the image, so treating a click on it like a click on the image probably makes sense.  For wide images, there will be a space below the image that is blank background, but treating that blank area in one way and a blank area one pixel lower in a different way would seem very odd.  Also note that there can be multiple album art columns with different widths.  The minimum height of the group is determined by the widest of these columns.

The shape of an image is only known while it is being rendered onto the playlist.  After that it could possibly be determined by a request to examine the pixbuf, but in some cases the pixbuf might not be available synchronously.  The actual image size cannot currently be stored on any data structure since it is different for each album art column in each group.

Given the difficulties it might make sense to treat clicks anywhere on the album art column in the same way.

**Comment by cboxdoerfer** [comment] 2015-10-26 14:47
Thx, for having a look at that. And yes, I'm not sure if it is worth the effort, because making that work is really ugly. Being able to add multiple album art columns sucks ;) On my local branch I already did lots of improvements to that, and currently I'm experimenting with drawing an outline of the album art area on mouse hover. This helps a lot for non-square album art, but then again adds lots of new code.

**Comment by Lithopsian** [comment] 2015-10-27 14:15
The image itself can potentially occupy any of the area up to the height of all the rows, or the minimum height for that column, whichever is greater.  The minimum height can easily be calculated for any album art column, and the height of the rows is obvious enough.  In almost all cases the image is allowed to be as tall as the group, but with multiple album art columns the image is only currently allowed to expand to the minimum height of its own column even if the minimum height of another column is larger.  Maybe that could be tweaked, but it is so rare for there to be multiple album art columns as well as significantly non-square artwork.

Outlining that area might be confusing though.  There are no prelight effects anywhere else, and in almost all cases the outline will just be the entire height of the group.

**Comment by Lithopsian** [comment] 2015-10-27 14:27
Right clicks are also a bit confusing.  Clicking white space below the group rows deselects and doesn't display a menu.  Clicking white space below an image but level with a row selects all the rows and opens the context menu.  Clicking an image level with a row also selects all the rows and opens the menu.  Clicking an image below the bottom row selects all the rows, but doesn't open a menu.

**Comment by Lithopsian** [comment] 2015-11-02 21:02
I've had a quick look at the new fixes.  I haven't checked all the shift-clicks and such, but the album art column behaves better now.

**Comment by Lithopsian** [comment] 2015-11-03 11:58
I'm not so sure about the shift-click changes.  Shift-click on the whitespace is better than before, but I find the new shift-click on album art behaviour weird.  I know it is what Foobar does, but still very weird.  Maybe the alternative is worse?

**Comment by cboxdoerfer** [comment] 2015-11-03 12:57
Yes, I find it somewhat strange too, but everything else I tried felt even worse. Any idea what we might do instead?

**Comment by Lithopsian** [comment] 2015-11-03 14:35
I'll assume that trying to act on a particular row while clicking on the album art column is going to be too messy to implement and too confusing for users?

The ctrl-click behaviour gives me an idea how this might be more consistent with expected shift-click behaviour.  In the new code, ctrl-click on the album art column or group title selects the whole group and adds it to the existing selection.  Couldn't shift-click select the whole group *and everything else up to the current cursor*?  This would be like ctrl-click except "leave no gaps in the selection".

**Comment by Lithopsian** [comment] 2015-11-03 17:29
I'm seeing a change in playlist focus (?) behaviour.  When Deadbeef used to open, ctrl-F would open a search for play items.  Now it opens a tag search on the track properties widget, and only opens a play item search after clicking on the playlist.  Is that a change from this bug?  Something I broke?  Coincidental from different configs?

**Comment by Lithopsian** [comment] 2015-11-03 17:56
Another slight oddity.  Selecting ranges in a search playlist doesn't deselect items from the main playlist that are already selected.  This can leave discontinuous selections.  I was looking at all the hard-coded instances of PL_MAIN in ddbllistview.c, thinking these were a bad idea.  Turns out maybe there should be more instead of using the binding functions?

Context menu actions (eg. add to playqueue) also appear to act on all selected items, not just those in the search playlist.  Maybe intentional?

I think this is due to the hard-coding

**Comment by Alexey-Yakovenko** [comment] 2015-11-03 18:37
@Lithopsian 

> I'm seeing a change in playlist focus (?) behaviour. When Deadbeef used to open, ctrl-F would open a search for play items. Now it opens a tag search on the track properties widget, and only opens a play item search after clicking on the playlist. Is that a change from this bug? Something I broke? Coincidental from different configs?

The easiest way to tell is to build from an older revision, or from the 0.7 branch.

**Comment by cboxdoerfer** [comment] 2015-11-03 18:42
> I'll assume that trying to act on a particular row while clicking on the album art column is going to be too messy to implement and too confusing for users?

Implementing that is not messy at all. Probably a one-liner. But I think this would be pretty inconsistent with the other selection behavior (single click selects group, ctrl+single click toggles group, double click plays group, so SHIFT click should also do something on the whole group).

>The ctrl-click behaviour gives me an idea how this might be more consistent with expected shift-click behaviour. In the new code, ctrl-click on the album art column or group title selects the whole group and adds it to the existing selection. Couldn't shift-click select the whole group and everything else up to the current cursor? This would be like ctrl-click except "leave no gaps in the selection".

Actually that was the first thing I tried, since it seemed pretty intuitive and logical. However in practice it felt strange to me. But maybe I'm just too used to foobar2000s' behavior. I guess I'll prepare some builds for you guys, so you can try both approaches and then decide.

> I'm seeing a change in playlist focus (?) behaviour. When Deadbeef used to open, ctrl-F would open a search for play items. Now it opens a tag search on the track properties widget, and only opens a play item search after clicking on the playlist. Is that a change from this bug? Something I broke? Coincidental from different configs?

I don't think this has anything to do with this bug, and on my machines ctrl-F works as you expect it to. Did you change your layout recently? Maybe the track properties widget is the first focusable widget in your layout and therefore might handle the key events before deadbeef.

> Another slight oddity. Selecting ranges in a search playlist doesn't deselect items from the main playlist that are already selected. This can leave discontinuous selections. I was looking at all the hard-coded instances of PL_MAIN in ddbllistview.c, thinking these were a bad idea. Turns out maybe there should be more instead of using the binding functions?

Hm, I can't reproduce that. selection in normal and search list are both in sync here no matter where I change the selection.

> Context menu actions (eg. add to playqueue) also appear to act on all selected items, not just those in the search playlist. Maybe intentional?

What do you mean with all "selected items, not just those in the search playlist"? Selection is supposed to be in sync, so everything that is selected in the search list is also selected in the normal list and vice versa. Add to playqueue and some other actions were always applied on the whole selection.

**Comment by Alexey-Yakovenko** [comment] 2015-11-03 18:43
> Another slight oddity. Selecting ranges in a search playlist doesn't deselect items from the main playlist that are already selected.

I think it's a regression from the PR 1313 (wow what a number!)

**Comment by Lithopsian** [comment] 2015-11-03 19:47
To clarify the (de-)selection issue.  Search and main playlist selections are designed to be in sync, but it is still possible to change the selection in the main playlist, and possible to select items that are not in the current search playlist.  You can do it with the mouse, but also ctrl-A in the search playlist selects all play items in the main playlist.

**Comment by cboxdoerfer** [comment] 2015-11-03 20:02
Yes, but as far as I can tell everything works as expected and as always. E.g. there are three tracks in the main playlist: A, B, C. If I select B, then open the search window, B gets selected (*). now if I search for something so that A and C are found, A and C show up in the search list and are selected both in search and main playlist, nothing else. If I now select B in the main playlist, A and C get deselected (both in search and main playlist) and only B is selected. If I now manually select C in the search list, B gets deselcted in the main playlist and only C is selected in both lists (*). Same applies to actions like area selection, SHIFT-cursor selection, CTRL-selection, ...

Or do you mean something else?

(*) just like in deadbeef 0.6.2

**Comment by Alexey-Yakovenko** [comment] 2015-11-03 20:04
@Lithopsian 

> ctrl-A in the search playlist selects all play items in the main playlist.

That's a (not previously known) bug, should be easy to fix. But are there any other issues? You're saying there are problems, but not saying what are they. And it's unclear whether they are new after the PR 1313, or they were present before.

> Items selected in the main list, but not in the search list, remain selected when shift-clicking in the search list.

And this sounds like expected behaviour.

**Comment by Lithopsian** [comment] 2015-11-03 20:04
I tried an older build, which is how I know it didn't do this before.  The layout, but knowing that it works for someone else, I tried all sorts of layouts, and building the same layout in different orders.  No joy.  I have a fairly typical layout, playlist along the left side, track properties on the right of a splitter.

Of course I missed the most obvious things.  In GTK2, the playlist appears to have focus at startup (although not any particular play item), while in GTK3 the selected properties widget gets the focus.  Perhaps just a timing issue?  Should it be made more explicit in the code?  I find it very frustrating, but perhaps just because I'm used to it being one way.

**Comment by Alexey-Yakovenko** [comment] 2015-11-03 20:10
@Lithopsian I just checked, the ctrl+a selection is not a regression, and doesn't have anything to do with the issue #1293. The GTK2 vs GTK3 playlist focus doesn't seem to have anything to do with this issue either, and most likely is not a new thing.

I understand your frustration, but please let's keep the discussion on-topic, and only write stuff relevant to the changes made by PR 1313. Feel free to create new bug reports about anything unrelated to this ticket.

**Comment by cboxdoerfer** [comment] 2015-11-06 12:26
When dragging some track and hovering the album art, what do you guys like better:

1. Place the drop position at the beginning of that group. (that's what foobar2000s simplaylist does)
2. Place the it at the end of that group.
3. Ignore the album art and place it before/after the track that matches y coordinates of the mouse pointer (that's what we do currently)

**Comment by Alexey-Yakovenko** [comment] 2015-11-06 12:29
I vote for **1.**

**Comment by Lithopsian** [comment] 2015-11-06 12:33
I like the current behaviour (3?).  Option 1 can cause big jumps in the marker position for small horizontal movements, and I guess option 2 would be the same.

**Comment by Alexey-Yakovenko** [comment] 2016-01-18 12:37
@cboxdoerfer is this fixed now?

**Comment by cboxdoerfer** [comment] 2016-01-19 08:48
Yes.

**Closed** 2016-01-19 08:48 UTC
