### ISSUE TITLE
I can't mark the text which I'm going to copy like other applications do.

### ISSUE THREAD

**Issue by laichiaheng** [Alexey-Yakovenko/deadbeef#1426] opened 2015-12-30 07:06 UTC
I want to copy the name of the song in properties, but I can't.
https://youtu.be/TwmWZl-kIR0

**Comment by Alexey-Yakovenko** [comment] 2015-12-30 12:20
Duplicate of bug #1111

**Closed by Alexey-Yakovenko** 2015-12-30 12:20 UTC
